/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountPoints,
  AccountPointsMe,
  PaginatedAccountPointsList,
} from '../models/index';
import {
    AccountPointsFromJSON,
    AccountPointsToJSON,
    AccountPointsMeFromJSON,
    AccountPointsMeToJSON,
    PaginatedAccountPointsListFromJSON,
    PaginatedAccountPointsListToJSON,
} from '../models/index';

export interface GamificationAccountPointsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    account?: string;
    pointTotal?: number;
    pointTotalGte?: number;
    pointTotalLte?: number;
    updatedAt?: Date;
    updatedAtGte?: Date;
    updatedAtLte?: Date;
}

export interface GamificationAccountPointsMeRequest {
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface GamificationAccountPointsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class AccountPointsApi extends runtime.BaseAPI {

    /**
     * Current point balances per account
     * List
     */
    async gamificationAccountPointsListRaw(requestParameters: GamificationAccountPointsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAccountPointsList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['pointTotal'] != null) {
            queryParameters['point_total'] = requestParameters['pointTotal'];
        }

        if (requestParameters['pointTotalGte'] != null) {
            queryParameters['point_total__gte'] = requestParameters['pointTotalGte'];
        }

        if (requestParameters['pointTotalLte'] != null) {
            queryParameters['point_total__lte'] = requestParameters['pointTotalLte'];
        }

        if (requestParameters['updatedAt'] != null) {
            queryParameters['updated_at'] = (requestParameters['updatedAt'] as any).toISOString();
        }

        if (requestParameters['updatedAtGte'] != null) {
            queryParameters['updated_at__gte'] = (requestParameters['updatedAtGte'] as any).toISOString();
        }

        if (requestParameters['updatedAtLte'] != null) {
            queryParameters['updated_at__lte'] = (requestParameters['updatedAtLte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/account_points/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAccountPointsListFromJSON(jsonValue));
    }

    /**
     * Current point balances per account
     * List
     */
    async gamificationAccountPointsList(requestParameters: GamificationAccountPointsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAccountPointsList> {
        const response = await this.gamificationAccountPointsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Current point balances per account
     * Current User Point Total
     */
    async gamificationAccountPointsMeRaw(requestParameters: GamificationAccountPointsMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountPointsMe>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/account_points/me/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountPointsMeFromJSON(jsonValue));
    }

    /**
     * Current point balances per account
     * Current User Point Total
     */
    async gamificationAccountPointsMe(requestParameters: GamificationAccountPointsMeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountPointsMe> {
        const response = await this.gamificationAccountPointsMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Current point balances per account
     * Retrieve
     */
    async gamificationAccountPointsRetrieveRaw(requestParameters: GamificationAccountPointsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountPoints>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamificationAccountPointsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/account_points/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountPointsFromJSON(jsonValue));
    }

    /**
     * Current point balances per account
     * Retrieve
     */
    async gamificationAccountPointsRetrieve(requestParameters: GamificationAccountPointsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountPoints> {
        const response = await this.gamificationAccountPointsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
