/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountProgress,
  AccountProgressMe,
  PaginatedAccountProgressList,
} from '../models/index';
import {
    AccountProgressFromJSON,
    AccountProgressToJSON,
    AccountProgressMeFromJSON,
    AccountProgressMeToJSON,
    PaginatedAccountProgressListFromJSON,
    PaginatedAccountProgressListToJSON,
} from '../models/index';

export interface GamificationAccountProgressListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    account?: string;
    level?: number;
    levelGte?: number;
    levelLte?: number;
    pointTotal?: number;
    pointTotalGte?: number;
    pointTotalLte?: number;
    updatedAt?: Date;
    updatedAtGte?: Date;
    updatedAtLte?: Date;
}

export interface GamificationAccountProgressMeRequest {
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface GamificationAccountProgressRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class AccountProgressApi extends runtime.BaseAPI {

    /**
     * Current progress (points and level) per account
     * List
     */
    async gamificationAccountProgressListRaw(requestParameters: GamificationAccountProgressListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAccountProgressList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['levelGte'] != null) {
            queryParameters['level__gte'] = requestParameters['levelGte'];
        }

        if (requestParameters['levelLte'] != null) {
            queryParameters['level__lte'] = requestParameters['levelLte'];
        }

        if (requestParameters['pointTotal'] != null) {
            queryParameters['point_total'] = requestParameters['pointTotal'];
        }

        if (requestParameters['pointTotalGte'] != null) {
            queryParameters['point_total__gte'] = requestParameters['pointTotalGte'];
        }

        if (requestParameters['pointTotalLte'] != null) {
            queryParameters['point_total__lte'] = requestParameters['pointTotalLte'];
        }

        if (requestParameters['updatedAt'] != null) {
            queryParameters['updated_at'] = (requestParameters['updatedAt'] as any).toISOString();
        }

        if (requestParameters['updatedAtGte'] != null) {
            queryParameters['updated_at__gte'] = (requestParameters['updatedAtGte'] as any).toISOString();
        }

        if (requestParameters['updatedAtLte'] != null) {
            queryParameters['updated_at__lte'] = (requestParameters['updatedAtLte'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/account_progress/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAccountProgressListFromJSON(jsonValue));
    }

    /**
     * Current progress (points and level) per account
     * List
     */
    async gamificationAccountProgressList(requestParameters: GamificationAccountProgressListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAccountProgressList> {
        const response = await this.gamificationAccountProgressListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Current progress (points and level) per account
     * Current User Progress
     */
    async gamificationAccountProgressMeRaw(requestParameters: GamificationAccountProgressMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountProgressMe>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/account_progress/me/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountProgressMeFromJSON(jsonValue));
    }

    /**
     * Current progress (points and level) per account
     * Current User Progress
     */
    async gamificationAccountProgressMe(requestParameters: GamificationAccountProgressMeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountProgressMe> {
        const response = await this.gamificationAccountProgressMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Current progress (points and level) per account
     * Retrieve
     */
    async gamificationAccountProgressRetrieveRaw(requestParameters: GamificationAccountProgressRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountProgress>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamificationAccountProgressRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/account_progress/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountProgressFromJSON(jsonValue));
    }

    /**
     * Current progress (points and level) per account
     * Retrieve
     */
    async gamificationAccountProgressRetrieve(requestParameters: GamificationAccountProgressRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountProgress> {
        const response = await this.gamificationAccountProgressRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
