/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RecordActivityRequest,
  StreakState,
} from '../models/index';
import {
    RecordActivityRequestFromJSON,
    RecordActivityRequestToJSON,
    StreakStateFromJSON,
    StreakStateToJSON,
} from '../models/index';

export interface GamificationActivityRecordRequest {
    recordActivityRequest: RecordActivityRequest;
}

/**
 * 
 */
export class ActivityApi extends runtime.BaseAPI {

    /**
     * Record real learning activities that may advance the daily streak
     * Record Learning Activity
     */
    async gamificationActivityRecordRaw(requestParameters: GamificationActivityRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakState>> {
        if (requestParameters['recordActivityRequest'] == null) {
            throw new runtime.RequiredError(
                'recordActivityRequest',
                'Required parameter "recordActivityRequest" was null or undefined when calling gamificationActivityRecord().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/activity/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecordActivityRequestToJSON(requestParameters['recordActivityRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakStateFromJSON(jsonValue));
    }

    /**
     * Record real learning activities that may advance the daily streak
     * Record Learning Activity
     */
    async gamificationActivityRecord(requestParameters: GamificationActivityRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakState> {
        const response = await this.gamificationActivityRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
