/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AllowedRolePermission,
  PaginatedAllowedRolePermissionList,
} from '../models/index';
import {
    AllowedRolePermissionFromJSON,
    AllowedRolePermissionToJSON,
    PaginatedAllowedRolePermissionListFromJSON,
    PaginatedAllowedRolePermissionListToJSON,
} from '../models/index';

export interface AuthAllowedRolePermissionsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    permission?: number;
    scopeType?: number;
}

export interface AuthAllowedRolePermissionsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class AllowedRolePermissionsApi extends runtime.BaseAPI {

    /**
     * Allowed permissions for the roles of a given scope type
     * List
     */
    async authAllowedRolePermissionsListRaw(requestParameters: AuthAllowedRolePermissionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAllowedRolePermissionList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['permission'] != null) {
            queryParameters['permission'] = requestParameters['permission'];
        }

        if (requestParameters['scopeType'] != null) {
            queryParameters['scope_type'] = requestParameters['scopeType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/auth/allowed_role_permissions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAllowedRolePermissionListFromJSON(jsonValue));
    }

    /**
     * Allowed permissions for the roles of a given scope type
     * List
     */
    async authAllowedRolePermissionsList(requestParameters: AuthAllowedRolePermissionsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAllowedRolePermissionList> {
        const response = await this.authAllowedRolePermissionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Allowed permissions for the roles of a given scope type
     * Retrieve
     */
    async authAllowedRolePermissionsRetrieveRaw(requestParameters: AuthAllowedRolePermissionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllowedRolePermission>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling authAllowedRolePermissionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/auth/allowed_role_permissions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllowedRolePermissionFromJSON(jsonValue));
    }

    /**
     * Allowed permissions for the roles of a given scope type
     * Retrieve
     */
    async authAllowedRolePermissionsRetrieve(requestParameters: AuthAllowedRolePermissionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllowedRolePermission> {
        const response = await this.authAllowedRolePermissionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
