/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CourseProgress,
  PaginatedCourseProgressList,
} from '../models/index';
import {
    CourseProgressFromJSON,
    CourseProgressToJSON,
    PaginatedCourseProgressListFromJSON,
    PaginatedCourseProgressListToJSON,
} from '../models/index';

export interface GamificationCourseProgressListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    account?: string;
    course?: string;
    courseLevel?: number;
    courseLevelGte?: number;
    courseLevelLte?: number;
    coursePoints?: number;
    coursePointsGte?: number;
    coursePointsLte?: number;
    courseProgress?: number;
    courseProgressGte?: number;
    courseProgressLte?: number;
}

export interface GamificationCourseProgressRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class CourseProgressApi extends runtime.BaseAPI {

    /**
     * Current progress per course and account
     * List
     */
    async gamificationCourseProgressListRaw(requestParameters: GamificationCourseProgressListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedCourseProgressList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['course'] != null) {
            queryParameters['course'] = requestParameters['course'];
        }

        if (requestParameters['courseLevel'] != null) {
            queryParameters['course_level'] = requestParameters['courseLevel'];
        }

        if (requestParameters['courseLevelGte'] != null) {
            queryParameters['course_level__gte'] = requestParameters['courseLevelGte'];
        }

        if (requestParameters['courseLevelLte'] != null) {
            queryParameters['course_level__lte'] = requestParameters['courseLevelLte'];
        }

        if (requestParameters['coursePoints'] != null) {
            queryParameters['course_points'] = requestParameters['coursePoints'];
        }

        if (requestParameters['coursePointsGte'] != null) {
            queryParameters['course_points__gte'] = requestParameters['coursePointsGte'];
        }

        if (requestParameters['coursePointsLte'] != null) {
            queryParameters['course_points__lte'] = requestParameters['coursePointsLte'];
        }

        if (requestParameters['courseProgress'] != null) {
            queryParameters['course_progress'] = requestParameters['courseProgress'];
        }

        if (requestParameters['courseProgressGte'] != null) {
            queryParameters['course_progress__gte'] = requestParameters['courseProgressGte'];
        }

        if (requestParameters['courseProgressLte'] != null) {
            queryParameters['course_progress__lte'] = requestParameters['courseProgressLte'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/course_progress/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedCourseProgressListFromJSON(jsonValue));
    }

    /**
     * Current progress per course and account
     * List
     */
    async gamificationCourseProgressList(requestParameters: GamificationCourseProgressListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedCourseProgressList> {
        const response = await this.gamificationCourseProgressListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Current progress per course and account
     * Retrieve
     */
    async gamificationCourseProgressRetrieveRaw(requestParameters: GamificationCourseProgressRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseProgress>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamificationCourseProgressRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/course_progress/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseProgressFromJSON(jsonValue));
    }

    /**
     * Current progress per course and account
     * Retrieve
     */
    async gamificationCourseProgressRetrieve(requestParameters: GamificationCourseProgressRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseProgress> {
        const response = await this.gamificationCourseProgressRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
