/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTMLLibraryText,
  PaginatedHTMLLibraryTextList,
} from '../models/index';
import {
    HTMLLibraryTextFromJSON,
    HTMLLibraryTextToJSON,
    PaginatedHTMLLibraryTextListFromJSON,
    PaginatedHTMLLibraryTextListToJSON,
} from '../models/index';

export interface CoreHtmlLibraryTextsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    language?: string;
    parentAuthorIcontains?: string;
    parentId?: string;
    parentNameIcontains?: string;
    parentOrganizationIcontains?: string;
    shortDescriptionIcontains?: string;
}

export interface CoreHtmlLibraryTextsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class HTMLLibraryTextsApi extends runtime.BaseAPI {

    /**
     * HTML Libraries Texts
     * List
     */
    async coreHtmlLibraryTextsListRaw(requestParameters: CoreHtmlLibraryTextsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedHTMLLibraryTextList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['parentAuthorIcontains'] != null) {
            queryParameters['parent__author__icontains'] = requestParameters['parentAuthorIcontains'];
        }

        if (requestParameters['parentId'] != null) {
            queryParameters['parent__id'] = requestParameters['parentId'];
        }

        if (requestParameters['parentNameIcontains'] != null) {
            queryParameters['parent__name__icontains'] = requestParameters['parentNameIcontains'];
        }

        if (requestParameters['parentOrganizationIcontains'] != null) {
            queryParameters['parent__organization__icontains'] = requestParameters['parentOrganizationIcontains'];
        }

        if (requestParameters['shortDescriptionIcontains'] != null) {
            queryParameters['short_description__icontains'] = requestParameters['shortDescriptionIcontains'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/core/html_library/texts/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedHTMLLibraryTextListFromJSON(jsonValue));
    }

    /**
     * HTML Libraries Texts
     * List
     */
    async coreHtmlLibraryTextsList(requestParameters: CoreHtmlLibraryTextsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedHTMLLibraryTextList> {
        const response = await this.coreHtmlLibraryTextsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * HTML Libraries Texts
     * Retrieve
     */
    async coreHtmlLibraryTextsRetrieveRaw(requestParameters: CoreHtmlLibraryTextsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HTMLLibraryText>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coreHtmlLibraryTextsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/core/html_library/texts/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HTMLLibraryTextFromJSON(jsonValue));
    }

    /**
     * HTML Libraries Texts
     * Retrieve
     */
    async coreHtmlLibraryTextsRetrieve(requestParameters: CoreHtmlLibraryTextsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HTMLLibraryText> {
        const response = await this.coreHtmlLibraryTextsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
