/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedRewardEventLogList,
  RewardEventLog,
  TriggerRewardEventLogRequest,
  TriggerRewardEventLogResponse,
} from '../models/index';
import {
    PaginatedRewardEventLogListFromJSON,
    PaginatedRewardEventLogListToJSON,
    RewardEventLogFromJSON,
    RewardEventLogToJSON,
    TriggerRewardEventLogRequestFromJSON,
    TriggerRewardEventLogRequestToJSON,
    TriggerRewardEventLogResponseFromJSON,
    TriggerRewardEventLogResponseToJSON,
} from '../models/index';

export interface GamificationRewardEventLogListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    account?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    eventType?: string;
    eventTypeIcontains?: string;
    pointsDelta?: number;
    pointsDeltaGte?: number;
    pointsDeltaLte?: number;
    reward?: string;
}

export interface GamificationRewardEventLogRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface GamificationRewardEventLogTriggerRequest {
    triggerRewardEventLogRequest: TriggerRewardEventLogRequest;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class RewardEventLogApi extends runtime.BaseAPI {

    /**
     * Reward event log (audit log)
     * List
     */
    async gamificationRewardEventLogListRaw(requestParameters: GamificationRewardEventLogListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedRewardEventLogList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['eventTypeIcontains'] != null) {
            queryParameters['event_type__icontains'] = requestParameters['eventTypeIcontains'];
        }

        if (requestParameters['pointsDelta'] != null) {
            queryParameters['points_delta'] = requestParameters['pointsDelta'];
        }

        if (requestParameters['pointsDeltaGte'] != null) {
            queryParameters['points_delta__gte'] = requestParameters['pointsDeltaGte'];
        }

        if (requestParameters['pointsDeltaLte'] != null) {
            queryParameters['points_delta__lte'] = requestParameters['pointsDeltaLte'];
        }

        if (requestParameters['reward'] != null) {
            queryParameters['reward'] = requestParameters['reward'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/reward_event_log/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedRewardEventLogListFromJSON(jsonValue));
    }

    /**
     * Reward event log (audit log)
     * List
     */
    async gamificationRewardEventLogList(requestParameters: GamificationRewardEventLogListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedRewardEventLogList> {
        const response = await this.gamificationRewardEventLogListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reward event log (audit log)
     * Retrieve
     */
    async gamificationRewardEventLogRetrieveRaw(requestParameters: GamificationRewardEventLogRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardEventLog>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamificationRewardEventLogRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/reward_event_log/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardEventLogFromJSON(jsonValue));
    }

    /**
     * Reward event log (audit log)
     * Retrieve
     */
    async gamificationRewardEventLogRetrieve(requestParameters: GamificationRewardEventLogRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardEventLog> {
        const response = await this.gamificationRewardEventLogRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reward event log (audit log)
     * Trigger Reward Event
     */
    async gamificationRewardEventLogTriggerRaw(requestParameters: GamificationRewardEventLogTriggerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerRewardEventLogResponse>> {
        if (requestParameters['triggerRewardEventLogRequest'] == null) {
            throw new runtime.RequiredError(
                'triggerRewardEventLogRequest',
                'Required parameter "triggerRewardEventLogRequest" was null or undefined when calling gamificationRewardEventLogTrigger().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/reward_event_log/trigger/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerRewardEventLogRequestToJSON(requestParameters['triggerRewardEventLogRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerRewardEventLogResponseFromJSON(jsonValue));
    }

    /**
     * Reward event log (audit log)
     * Trigger Reward Event
     */
    async gamificationRewardEventLogTrigger(requestParameters: GamificationRewardEventLogTriggerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerRewardEventLogResponse> {
        const response = await this.gamificationRewardEventLogTriggerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
