/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedRewardList,
  Reward,
} from '../models/index';
import {
    PaginatedRewardListFromJSON,
    PaginatedRewardListToJSON,
    RewardFromJSON,
    RewardToJSON,
} from '../models/index';

export interface GamificationRewardsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    rewardType?: string;
    rewardTypeIcontains?: string;
    value?: number;
    valueGte?: number;
    valueLte?: number;
}

export interface GamificationRewardsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class RewardsApi extends runtime.BaseAPI {

    /**
     * Rewards
     * List
     */
    async gamificationRewardsListRaw(requestParameters: GamificationRewardsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedRewardList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['rewardType'] != null) {
            queryParameters['reward_type'] = requestParameters['rewardType'];
        }

        if (requestParameters['rewardTypeIcontains'] != null) {
            queryParameters['reward_type__icontains'] = requestParameters['rewardTypeIcontains'];
        }

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        if (requestParameters['valueGte'] != null) {
            queryParameters['value__gte'] = requestParameters['valueGte'];
        }

        if (requestParameters['valueLte'] != null) {
            queryParameters['value__lte'] = requestParameters['valueLte'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/rewards/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedRewardListFromJSON(jsonValue));
    }

    /**
     * Rewards
     * List
     */
    async gamificationRewardsList(requestParameters: GamificationRewardsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedRewardList> {
        const response = await this.gamificationRewardsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rewards
     * Retrieve
     */
    async gamificationRewardsRetrieveRaw(requestParameters: GamificationRewardsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamificationRewardsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/rewards/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Rewards
     * Retrieve
     */
    async gamificationRewardsRetrieve(requestParameters: GamificationRewardsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.gamificationRewardsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
