/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedRewardEventList,
  RewardEvent,
  TriggerRewardEventRequest,
  TriggerRewardEventResponse,
} from '../models/index';
import {
    PaginatedRewardEventListFromJSON,
    PaginatedRewardEventListToJSON,
    RewardEventFromJSON,
    RewardEventToJSON,
    TriggerRewardEventRequestFromJSON,
    TriggerRewardEventRequestToJSON,
    TriggerRewardEventResponseFromJSON,
    TriggerRewardEventResponseToJSON,
} from '../models/index';

export interface GamificationRewardEventTriggerRequest {
    triggerRewardEventRequest: TriggerRewardEventRequest;
    expand?: string;
    fields?: string;
    omit?: string;
}

export interface GamificationRewardEventsListRequest {
    expand?: string;
    fields?: string;
    omit?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sort?: string;
    account?: string;
    createdAt?: Date;
    createdAtGte?: Date;
    createdAtLte?: Date;
    eventType?: string;
    eventTypeIcontains?: string;
    pointsDelta?: number;
    pointsDeltaGte?: number;
    pointsDeltaLte?: number;
    reward?: string;
}

export interface GamificationRewardEventsRetrieveRequest {
    id: string;
    expand?: string;
    fields?: string;
    omit?: string;
}

/**
 * 
 */
export class RewardEventsApi extends runtime.BaseAPI {

    /**
     * Reward events (audit log)
     * Trigger Reward Event
     */
    async gamificationRewardEventTriggerRaw(requestParameters: GamificationRewardEventTriggerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerRewardEventResponse>> {
        if (requestParameters['triggerRewardEventRequest'] == null) {
            throw new runtime.RequiredError(
                'triggerRewardEventRequest',
                'Required parameter "triggerRewardEventRequest" was null or undefined when calling gamificationRewardEventTrigger().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/reward_events/trigger/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerRewardEventRequestToJSON(requestParameters['triggerRewardEventRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerRewardEventResponseFromJSON(jsonValue));
    }

    /**
     * Reward events (audit log)
     * Trigger Reward Event
     */
    async gamificationRewardEventTrigger(requestParameters: GamificationRewardEventTriggerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerRewardEventResponse> {
        const response = await this.gamificationRewardEventTriggerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reward events (audit log)
     * List
     */
    async gamificationRewardEventsListRaw(requestParameters: GamificationRewardEventsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedRewardEventList>> {
        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['_page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['_page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['_search'] = requestParameters['search'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['createdAt'] != null) {
            queryParameters['created_at'] = (requestParameters['createdAt'] as any).toISOString();
        }

        if (requestParameters['createdAtGte'] != null) {
            queryParameters['created_at__gte'] = (requestParameters['createdAtGte'] as any).toISOString();
        }

        if (requestParameters['createdAtLte'] != null) {
            queryParameters['created_at__lte'] = (requestParameters['createdAtLte'] as any).toISOString();
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['eventTypeIcontains'] != null) {
            queryParameters['event_type__icontains'] = requestParameters['eventTypeIcontains'];
        }

        if (requestParameters['pointsDelta'] != null) {
            queryParameters['points_delta'] = requestParameters['pointsDelta'];
        }

        if (requestParameters['pointsDeltaGte'] != null) {
            queryParameters['points_delta__gte'] = requestParameters['pointsDeltaGte'];
        }

        if (requestParameters['pointsDeltaLte'] != null) {
            queryParameters['points_delta__lte'] = requestParameters['pointsDeltaLte'];
        }

        if (requestParameters['reward'] != null) {
            queryParameters['reward'] = requestParameters['reward'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/reward_events/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedRewardEventListFromJSON(jsonValue));
    }

    /**
     * Reward events (audit log)
     * List
     */
    async gamificationRewardEventsList(requestParameters: GamificationRewardEventsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedRewardEventList> {
        const response = await this.gamificationRewardEventsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reward events (audit log)
     * Retrieve
     */
    async gamificationRewardEventsRetrieveRaw(requestParameters: GamificationRewardEventsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardEvent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gamificationRewardEventsRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['_expand'] = requestParameters['expand'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['_fields'] = requestParameters['fields'];
        }

        if (requestParameters['omit'] != null) {
            queryParameters['_omit'] = requestParameters['omit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/reward_events/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardEventFromJSON(jsonValue));
    }

    /**
     * Reward events (audit log)
     * Retrieve
     */
    async gamificationRewardEventsRetrieve(requestParameters: GamificationRewardEventsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardEvent> {
        const response = await this.gamificationRewardEventsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
