/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StreakState,
} from '../models/index';
import {
    StreakStateFromJSON,
    StreakStateToJSON,
} from '../models/index';

/**
 * 
 */
export class StreakApi extends runtime.BaseAPI {

    /**
     * Daily learning streak of the current user
     * Current User Streak
     */
    async gamificationStreakRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StreakState>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["sessionId"] = await this.configuration.apiKey("sessionId"); // SessionAuthentication authentication
        }

        const response = await this.request({
            path: `/api/gamification/streak/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StreakStateFromJSON));
    }

    /**
     * Daily learning streak of the current user
     * Current User Streak
     */
    async gamificationStreakRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StreakState>> {
        const response = await this.gamificationStreakRetrieveRaw(initOverrides);
        return await response.value();
    }

}
