# Generated by Django 6.0.4 on 2026-05-18 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('reward_type', models.CharField(db_column='type', db_index=True, max_length=64, verbose_name='Reward Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Value')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['reward_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='AccountPoints',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('point_total', models.IntegerField(default=0, verbose_name='Point Total')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_points', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account Points',
                'verbose_name_plural': 'Account Points',
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='Event Type')),
                ('points_delta', models.IntegerField(verbose_name='Points Delta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('context', models.JSONField(blank=True, db_column='context_json', default=dict, verbose_name='Context')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='openbook_gamification.reward', verbose_name='Reward')),
            ],
            options={
                'verbose_name': 'Reward Event',
                'verbose_name_plural': 'Reward Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Level')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['account', 'name'],
                'constraints': [models.UniqueConstraint(fields=('account', 'name'), name='unique_skill_per_account')],
            },
        ),
    ]
