# Generated by Django 6.0.4 on 2026-05-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.IntegerField(verbose_name='Value'),
        ),
    ]
