# OpenBook: Interactive Online Textbooks - Server
# © 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
# Ledejna Salihi (@LedejnaSalihi)
# Lars Zieger (@lzieger03)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Generated by Django 6.0.4 on 2026-05-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def recompute_levels(apps, schema_editor):
    AccountProgress = apps.get_model("openbook_gamification", "AccountProgress")
    LevelThreshold  = apps.get_model("openbook_gamification", "LevelThreshold")

    for progress in AccountProgress.objects.all():
        threshold = (
            LevelThreshold.objects
            .filter(min_points__lte=progress.point_total)
            .order_by("-min_points", "-level")
            .first()
        )

        level = threshold.level if threshold else 1

        if progress.level != level:
            progress.level = level
            progress.save(update_fields=["level"])


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_gamification', '0003_rename_accountpoints_to_accountprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThreshold',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='Level')),
                ('min_points', models.IntegerField(db_index=True, verbose_name='Required Points')),
            ],
            options={
                'verbose_name': 'Level Threshold',
                'verbose_name_plural': 'Level Thresholds',
                'ordering': ['min_points', 'level'],
            },
        ),
        migrations.AlterField(
            model_name='accountprogress',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_progress', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='accountprogress',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Value'),
        ),
        migrations.RunPython(recompute_levels, migrations.RunPython.noop),
    ]
