# Generated by Django 6.0.4 on 2026-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_gamification', '0004_levelthreshold_alter_accountprogress_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='value',
            field=models.IntegerField(verbose_name='Value'),
        ),
    ]
