# OpenBook: Interactive Online Textbooks - Server
# © 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
# Ledejna Salihi (@LedejnaSalihi)
# Lars Zieger (@lzieger03)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Generated by Django 6.0.4 on 2026-05-21 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_gamification', '0006_rename_rewardevent_to_rewardeventlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardeventlog',
            name='points_delta',
            field=models.IntegerField(default=0, verbose_name='Points Delta'),
        ),
        migrations.AlterField(
            model_name='rewardeventlog',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='openbook_gamification.reward', verbose_name='Reward'),
        ),
        migrations.CreateModel(
            name='AccountStreak',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Longest Streak')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='Last Active Date')),
                ('streak_freezes', models.PositiveIntegerField(default=0, verbose_name='Streak Freezes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_streak', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account Streak',
                'verbose_name_plural': 'Account Streaks',
                'db_table': 'openbook_gamification_account_streak',
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivityDay',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('activity_date', models.DateField(db_index=True, verbose_name='Activity Date')),
                ('activity_count', models.PositiveIntegerField(default=1, verbose_name='Activity Count')),
                ('first_activity_at', models.DateTimeField(verbose_name='First Activity At')),
                ('last_activity_at', models.DateTimeField(verbose_name='Last Activity At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account Activity Day',
                'verbose_name_plural': 'Account Activity Days',
                'db_table': 'openbook_gamification_account_activity_day',
                'ordering': ['-activity_date'],
                'constraints': [models.UniqueConstraint(fields=('account', 'activity_date'), name='unique_account_activity_day')],
            },
        ),
    ]
