# Generated by Django 6.0.4 on 2026-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_gamification', '0007_alter_rewardeventlog_points_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstreak',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active At'),
        ),
    ]
