# OpenBook: Interactive Online Textbooks - Server
# © 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
# Ledejna Salihi (@LedejnaSalihi)
# Lars Zieger (@lzieger03)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Generated by Django 6.0.4 on 2026-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_gamification', '0007_alter_rewardeventlog_points_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstreak',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active At'),
        ),
    ]
