# Generated by Django 6.0.4 on 2026-05-29 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_content', '0004_coursematerialpagerange_alter_course_options_and_more'),
        ('openbook_gamification', '0008_accountstreak_last_active_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('course_points', models.IntegerField(default=0, verbose_name='Course Points')),
                ('course_level', models.PositiveIntegerField(default=1, verbose_name='Course Level')),
                ('course_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Course Progress')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to='openbook_content.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progresses',
                'db_table': 'openbook_gamification_course_progress',
                'ordering': ['account', 'course'],
                'constraints': [models.UniqueConstraint(fields=('account', 'course'), name='unique_course_progress_per_account_and_course')],
            },
        ),
    ]
