<!--
OpenBook: Interactive Online Textbooks - Server
(c) 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
-->

<!--
@component
Kahoot-style multiple-choice quiz for a course. Questions are generated by the
assistant backend through the existing course chat WebSocket channel.
-->
<script lang="ts">
    import {onMount} from "svelte";
    import {push} from "svelte-spa-router";

    import {fetchMaterials} from "../../api/content.js";
    import {dashboardStore} from "../../stores/dashboard.store.js";
    import type {DashboardState} from "../../stores/dashboard.store.js";
    import {createQuizStore} from "../../stores/quiz.store.js";
    import type {QuizState} from "../../stores/quiz.store.js";

    let {params}: {params?: {id?: string}} = $props();

    interface TextbookChoice {
        id: string;
        name: string;
        skills: {id: string; name: string}[];
    }

    let state = $state<DashboardState>({
        isLoading: true,
        errorMessage: "",
        user: null,
        stats: null,
        skills: [],
        courses: [],
    });

    let reward = $state<{pointsAwarded: number; skillsAdvanced: string[]} | null>(null);

    const quiz = createQuizStore(() => params?.id, {
        // Once the backend confirms the quiz result, show what was earned and reload the
        // dashboard data so the new course and skill points are reflected immediately.
        onResultRecorded: (summary) => {
            reward = summary;
            dashboardStore.refresh();
        },
    });
    let quizState = $state<QuizState>({
        connection: "disconnected",
        isLoading: false,
        errorMessage: "",
        questions: [],
        contextSource: null,
        sources: [],
    });

    const letters = ["A", "B", "C", "D"];

    let index = $state(0);
    let selected = $state<number | null>(null);
    let score = $state(0);
    let finished = $state(false);
    let timer: ReturnType<typeof setTimeout> | null = null;

    // Textbook selection step shown before a quiz is generated.
    let textbooks = $state<TextbookChoice[]>([]);
    let textbooksLoading = $state(true);
    let textbooksError = $state("");
    let selectedTextbookId = $state<string | null>(null);
    let resultSubmitted = $state(false);

    onMount(() => {
        const unsubscribeDashboard = dashboardStore.subscribe((value) => {
            state = value;
        });

        if (state.courses.length === 0) {
            dashboardStore.refresh();
        }

        const unsubscribeQuiz = quiz.subscribe((value) => {
            quizState = value;
        });

        void loadTextbooks();

        return () => {
            unsubscribeDashboard();
            unsubscribeQuiz();
            if (timer) {
                clearTimeout(timer);
            }
            void quiz.disconnect();
        };
    });

    const courseTitle = $derived(
        state.courses.find((course) => course.id === params?.id)?.name ?? "Course",
    );
    const selecting = $derived(selectedTextbookId === null);
    const selectedTextbookName = $derived(
        textbooks.find((book) => book.id === selectedTextbookId)?.name ?? "",
    );
    const questions = $derived(quizState.questions);
    const current = $derived(questions[index] ?? null);
    const answered = $derived(selected !== null);
    const isBusy = $derived(
        quizState.isLoading
            || quizState.connection === "connecting"
            || quizState.connection === "wait_before_retry",
    );
    const progressPct = $derived(
        questions.length === 0
            ? 0
            : ((index + (selected !== null ? 1 : 0)) / questions.length) * 100,
    );

    function advance(): void {
        timer = null;
        if (index >= questions.length - 1) {
            finished = true;
            if (!resultSubmitted) {
                resultSubmitted = true;
                const normalized = questions.length ? score / questions.length : 0;
                void quiz.submitResult(normalized, 1);
            }
        } else {
            index += 1;
            selected = null;
        }
    }

    function choose(optionIndex: number): void {
        if (selected !== null || !current) {
            return;
        }

        selected = optionIndex;
        if (current.options[optionIndex]?.correct) {
            score += 1;
        }

        timer = setTimeout(advance, 950);
    }

    function restart(): void {
        index = 0;
        selected = null;
        score = 0;
        finished = false;
        resultSubmitted = false;
        reward = null;
    }

    async function loadTextbooks(): Promise<void> {
        const courseId = params?.id;
        if (!courseId) {
            textbooksLoading = false;
            textbooksError = "No course selected.";
            return;
        }

        textbooksLoading = true;
        textbooksError = "";

        try {
            const materials = await fetchMaterials(courseId);
            const choices: TextbookChoice[] = [];

            for (const material of materials) {
                // Only materials whose textbook reference was expanded are usable.
                if (material.textbook && typeof material.textbook === "object") {
                    choices.push({
                        id: material.textbook.id,
                        name: material.textbook.name,
                        skills: (material.textbook.skills ?? []).map((skill) => ({id: skill.id, name: skill.name})),
                    });
                }
            }

            textbooks = choices;
        } catch (error) {
            textbooksError = error instanceof Error ? error.message : String(error);
        } finally {
            textbooksLoading = false;
        }
    }

    async function chooseTextbook(textbookId: string): Promise<void> {
        selectedTextbookId = textbookId;
        await loadQuiz();
    }

    function backToSelection(): void {
        if (timer) {
            clearTimeout(timer);
            timer = null;
        }
        restart();
        selectedTextbookId = null;
    }

    async function loadQuiz(): Promise<void> {
        if (timer) {
            clearTimeout(timer);
            timer = null;
        }

        if (!selectedTextbookId) {
            return;
        }

        restart();
        await quiz.requestQuiz(5, selectedTextbookId);
    }
</script>

<div class="quiz">
    <header class="quiz-top">
        <button type="button" class="content-btn" onclick={() => window.history.back()}>
            Back
        </button>
        {#if !selecting && !finished}
            <div class="progress-track" aria-hidden="true">
                <div class="progress-fill" style="width: {progressPct}%"></div>
            </div>
        {/if}
    </header>

    {#if selecting}
        <section class="stage select-stage">
            <h1 class="course">{courseTitle}</h1>
            <p class="select-hint">Choose a textbook to be quizzed on.</p>

            {#if textbooksLoading}
                <div class="status-card">
                    <span class="loader" aria-hidden="true"></span>
                    <p>Loading textbooks...</p>
                </div>
            {:else if textbooksError}
                <div class="status-card error-card" role="alert">
                    <p>{textbooksError}</p>
                    <button type="button" class="btn btn-primary" onclick={() => loadTextbooks()}>Retry</button>
                </div>
            {:else if textbooks.length === 0}
                <div class="status-card">
                    <p>This course has no textbooks to quiz on yet.</p>
                </div>
            {:else}
                <div class="textbook-list">
                    {#each textbooks as book (book.id)}
                        <button type="button" class="textbook-card" onclick={() => chooseTextbook(book.id)}>
                            <span class="textbook-icon" aria-hidden="true">📘</span>
                            <span class="textbook-name">{book.name}</span>
                            {#if book.skills.length > 0}
                                <span class="textbook-skills">
                                    {#each book.skills as skill (skill.id)}
                                        <span class="textbook-skill">{skill.name}</span>
                                    {/each}
                                </span>
                            {:else}
                                <span class="textbook-skills empty">No skills yet</span>
                            {/if}
                        </button>
                    {/each}
                </div>
            {/if}
        </section>
    {:else if isBusy}
        <section class="stage status-stage" aria-live="polite">
            <h1 class="course">{courseTitle}</h1>
            <div class="status-card">
                <span class="loader" aria-hidden="true"></span>
                <p>Generating quiz...</p>
            </div>
        </section>
    {:else if quizState.errorMessage}
        <section class="stage status-stage">
            <h1 class="course">{courseTitle}</h1>
            <div class="status-card error-card" role="alert">
                <p>{quizState.errorMessage}</p>
                <button type="button" class="btn btn-primary" onclick={() => loadQuiz()}>Retry</button>
            </div>
        </section>
    {:else if finished}
        <section class="stage result">
            <h1 class="course">{courseTitle}</h1>
            {#if selectedTextbookName}
                <span class="progress-pill">{selectedTextbookName}</span>
            {/if}
            <div class="score-ring">{score}/{questions.length}</div>
            <p class="result-text">
                {score === questions.length ? "Perfect score." : "Keep practising."}
            </p>

            {#if reward}
                {#if reward.pointsAwarded > 0}
                    <div class="reward" role="status">
                        <span class="reward-points">+{reward.pointsAwarded} points</span>
                        {#if reward.skillsAdvanced.length > 0}
                            <span class="reward-skills">
                                Skill progress:
                                {#each reward.skillsAdvanced as skill (skill)}
                                    <span class="reward-skill">{skill}</span>
                                {/each}
                            </span>
                        {/if}
                    </div>
                {:else}
                    <p class="reward-none">No new points — beat your previous best score to earn more.</p>
                {/if}
            {/if}
            <div class="result-actions">
                <button type="button" class="btn btn-primary" onclick={restart}>Try again</button>
                <button type="button" class="btn btn-outline" onclick={() => loadQuiz()}>New quiz</button>
                <button type="button" class="btn btn-outline" onclick={backToSelection}>Change textbook</button>
                <button type="button" class="btn btn-ghost" onclick={() => push("/")}>Back to Dashboard</button>
            </div>
        </section>
    {:else if current}
        <section class="stage">
            <h1 class="course">{courseTitle}</h1>
            <span class="progress-pill">Question {index + 1} / {questions.length}</span>
            <h2 class="prompt">{current.prompt}</h2>

            <div class="answers">
                {#each current.options as option, optionIndex (option.text)}
                    <button
                        type="button"
                        class="answer c{optionIndex}"
                        class:correct={answered && option.correct}
                        class:wrong={answered && optionIndex === selected && !option.correct}
                        class:dim={answered && !option.correct && optionIndex !== selected}
                        disabled={answered}
                        onclick={() => choose(optionIndex)}
                    >
                        <span class="letter">{letters[optionIndex]}</span>
                        <span class="text">{option.text}</span>
                    </button>
                {/each}
            </div>
        </section>
    {:else}
        <section class="stage status-stage">
            <h1 class="course">{courseTitle}</h1>
            <div class="status-card">
                <p>No quiz questions were generated.</p>
                <button type="button" class="btn btn-primary" onclick={() => loadQuiz()}>Generate quiz</button>
            </div>
        </section>
    {/if}
</div>

<style>
    .quiz {
        flex: 1;
        min-height: 0;
        display: flex;
        flex-direction: column;
        width: 100%;
        background:
            radial-gradient(120% 70% at 50% 0%, color-mix(in oklab, var(--color-primary) 8%, transparent), transparent 55%),
            var(--color-base-200);
    }

    .quiz-top {
        flex: 0 0 auto;
        display: flex;
        align-items: center;
        gap: 1.5rem;
        padding: 1.25rem 1.5rem;
    }

    .content-btn {
        flex: 0 0 auto;
        padding: 0.5rem 1.25rem;
        border-radius: 0.75rem;
        font-weight: 600;
        color: color-mix(in oklab, var(--color-base-content) 80%, transparent);
        background: color-mix(in oklab, var(--color-base-100) 70%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-base-content) 14%, transparent);
        cursor: pointer;
    }

    .content-btn:hover {
        border-color: color-mix(in oklab, var(--color-primary) 45%, transparent);
    }

    .content-btn:focus-visible {
        outline: 2px solid var(--color-primary);
        outline-offset: 2px;
    }

    .progress-track {
        flex: 1 1 auto;
        height: 0.5rem;
        border-radius: 999px;
        overflow: hidden;
        background: color-mix(in oklab, var(--color-base-content) 12%, transparent);
    }

    .progress-fill {
        height: 100%;
        border-radius: 999px;
        background: linear-gradient(90deg, var(--color-primary), var(--color-success));
        transition: width 0.3s ease;
    }

    .stage {
        flex: 1;
        min-height: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 1.25rem;
        width: 90%;
        max-width: 64rem;
        margin: 0 auto;
        padding: 1rem 0 2.5rem;
    }

    .course {
        font-size: clamp(1.3rem, 2.4vw, 1.9rem);
        font-weight: 700;
        text-align: center;
        color: var(--color-base-content);
        text-shadow: 0 0 20px color-mix(in oklab, var(--color-primary) 40%, transparent);
    }

    .status-stage {
        max-width: 34rem;
    }

    .select-stage {
        justify-content: flex-start;
        padding-top: 2.5rem;
    }

    .select-hint {
        font-size: 1.1rem;
        font-weight: 600;
        color: color-mix(in oklab, var(--color-base-content) 80%, transparent);
        margin: 0;
    }

    .textbook-list {
        width: 100%;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr));
        /* Equal-height rows so every card lines up regardless of skill count. */
        grid-auto-rows: 1fr;
        gap: 1.1rem;
        margin-top: 0.5rem;
    }

    /* Uniform vertical card: icon badge on top, name, skills pinned to the bottom. */
    .textbook-card {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        gap: 0.85rem;
        height: 100%;
        padding: 1.25rem;
        border-radius: 1rem;
        cursor: pointer;
        text-align: left;
        color: var(--color-base-content);
        background: color-mix(in oklab, var(--color-base-100) 82%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-base-content) 12%, transparent);
        transition: transform 0.12s ease, border-color 0.2s ease, box-shadow 0.2s ease, background 0.2s ease;
        box-shadow: 0 4px 14px color-mix(in oklab, var(--color-base-content) 10%, transparent);
    }

    .textbook-card:hover {
        transform: translateY(-3px);
        background: color-mix(in oklab, var(--color-primary) 8%, transparent);
        border-color: color-mix(in oklab, var(--color-primary) 55%, transparent);
        box-shadow: 0 10px 24px color-mix(in oklab, var(--color-primary) 22%, transparent);
    }

    .textbook-card:focus-visible {
        outline: 3px solid var(--color-primary);
        outline-offset: 3px;
    }

    /* Icon sits in a soft rounded badge for a consistent header on every card. */
    .textbook-icon {
        flex: 0 0 auto;
        display: grid;
        place-items: center;
        width: 2.6rem;
        height: 2.6rem;
        border-radius: 0.8rem;
        font-size: 1.4rem;
        background: color-mix(in oklab, var(--color-primary) 16%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-primary) 28%, transparent);
    }

    .textbook-name {
        font-size: 1.1rem;
        font-weight: 700;
        line-height: 1.3;
        overflow-wrap: anywhere;
    }

    /* Tags pinned to the bottom (margin-top:auto) so cards stay visually aligned. */
    .textbook-skills {
        margin-top: auto;
        display: flex;
        flex-wrap: wrap;
        gap: 0.35rem;
    }

    .textbook-skills.empty {
        font-size: 0.72rem;
        font-weight: 500;
        color: color-mix(in oklab, var(--color-base-content) 45%, transparent);
    }

    .textbook-skill {
        font-size: 0.72rem;
        font-weight: 600;
        padding: 0.12rem 0.6rem;
        border-radius: 999px;
        color: var(--color-primary);
        background: color-mix(in oklab, var(--color-primary) 14%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-primary) 30%, transparent);
    }

    .status-card {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
        width: 100%;
        padding: 2rem;
        border-radius: 0.75rem;
        text-align: center;
        color: var(--color-base-content);
        background: color-mix(in oklab, var(--color-base-100) 82%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-primary) 24%, transparent);
    }

    .error-card {
        border-color: color-mix(in oklab, var(--color-error) 45%, transparent);
    }

    .loader {
        width: 2.25rem;
        height: 2.25rem;
        border-radius: 999px;
        border: 0.25rem solid color-mix(in oklab, var(--color-primary) 25%, transparent);
        border-top-color: var(--color-primary);
        animation: spin 0.8s linear infinite;
    }

    .progress-pill {
        padding: 0.3rem 1rem;
        border-radius: 999px;
        font-weight: 700;
        color: var(--color-primary);
        background: color-mix(in oklab, var(--color-primary) 16%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-primary) 35%, transparent);
    }

    .prompt {
        font-size: clamp(1.7rem, 3.6vw, 2.8rem);
        font-weight: 800;
        text-align: center;
        color: var(--color-base-content);
        text-shadow: 0 0 22px color-mix(in oklab, var(--color-primary) 35%, transparent);
        margin: 0.5rem 0 1rem;
    }

    .answers {
        width: 100%;
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 1.1rem;
    }

    .answer {
        display: flex;
        align-items: center;
        gap: 1rem;
        min-height: 5rem;
        padding: 1.4rem 1.5rem;
        border-radius: 1rem;
        border: none;
        font-family: ui-monospace, "SF Mono", Menlo, monospace;
        font-size: 1.2rem;
        font-weight: 700;
        cursor: pointer;
        transition: transform 0.12s ease, opacity 0.2s ease, box-shadow 0.2s ease;
        box-shadow: 0 6px 18px color-mix(in oklab, var(--color-base-content) 14%, transparent);
    }

    .answer:hover:not(:disabled) {
        transform: translateY(-3px);
    }

    .answer:focus-visible {
        outline: 3px solid var(--color-base-content);
        outline-offset: 3px;
    }

    .letter {
        display: grid;
        place-items: center;
        width: 2.1rem;
        height: 2.1rem;
        flex: 0 0 auto;
        border-radius: 0.6rem;
        font-family: inherit;
        background: color-mix(in oklab, currentColor 18%, transparent);
    }

    .text {
        flex: 1 1 auto;
        text-align: center;
        overflow-wrap: anywhere;
    }

    .answer.c0 {
        background: var(--color-error);
        color: var(--color-error-content);
    }

    .answer.c1 {
        background: var(--color-info);
        color: var(--color-info-content);
    }

    .answer.c2 {
        background: var(--color-warning);
        color: var(--color-warning-content);
    }

    .answer.c3 {
        background: var(--color-success);
        color: var(--color-success-content);
    }

    .answer.dim {
        opacity: 0.35;
    }

    .answer.correct {
        outline: 4px solid var(--color-base-content);
        outline-offset: 3px;
        transform: translateY(-3px);
    }

    .answer.wrong {
        opacity: 0.65;
        text-decoration: line-through;
    }

    .result {
        justify-content: center;
    }

    .score-ring {
        display: grid;
        place-items: center;
        width: 9rem;
        height: 9rem;
        border-radius: 999px;
        font-size: 2rem;
        font-weight: 800;
        color: var(--color-base-content);
        background: color-mix(in oklab, var(--color-primary) 14%, transparent);
        border: 4px solid color-mix(in oklab, var(--color-primary) 55%, transparent);
        box-shadow: 0 0 28px color-mix(in oklab, var(--color-primary) 35%, transparent);
    }

    .result-text {
        font-size: 1.2rem;
        font-weight: 600;
        color: color-mix(in oklab, var(--color-base-content) 80%, transparent);
    }

    .reward {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 0.5rem;
    }

    .reward-points {
        font-size: 1.4rem;
        font-weight: 800;
        padding: 0.25rem 1rem;
        border-radius: 999px;
        color: var(--color-primary-content);
        background: var(--color-primary);
        box-shadow: 0 0 16px color-mix(in oklab, var(--color-primary) 50%, transparent);
    }

    .reward-skills {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
        gap: 0.4rem;
        font-size: 0.9rem;
        color: color-mix(in oklab, var(--color-base-content) 70%, transparent);
    }

    .reward-skill {
        font-size: 0.8rem;
        font-weight: 600;
        padding: 0.1rem 0.6rem;
        border-radius: 999px;
        color: var(--color-primary);
        background: color-mix(in oklab, var(--color-primary) 14%, transparent);
        border: 1px solid color-mix(in oklab, var(--color-primary) 30%, transparent);
    }

    .reward-none {
        font-size: 0.9rem;
        color: color-mix(in oklab, var(--color-base-content) 60%, transparent);
    }

    .result-actions {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 1rem;
    }

    @keyframes spin {
        to {
            transform: rotate(360deg);
        }
    }

    @media (max-width: 40rem) {
        .answers {
            grid-template-columns: 1fr;
        }

        .quiz-top {
            gap: 0.75rem;
            padding: 1rem;
        }
    }
</style>
