# Generated by Django 6.0.4 on 2026-06-05 14:16

import django.db.models.deletion
import openbook.core.models.mixins.file
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_assistant', '0001_create_documents_vector_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantDocument',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('file_data', models.FileField(blank=True, upload_to=openbook.core.models.mixins.file.FileUploadMixin._calc_file_path, verbose_name='File Data')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('mime_type', models.CharField(blank=True, max_length=64, verbose_name='MIME Type')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Assistant Document',
                'verbose_name_plural': 'Assistant Documents',
                'ordering': ('title', 'file_name'),
            },
        ),
        migrations.CreateModel(
            name='AssistantDocumentChunk',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of the chunk inside the uploaded source document.', verbose_name='Position')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('embedding', models.BinaryField(blank=True, default=bytes, help_text='Serialized float32 embedding used by the vector search index.', verbose_name='Embedding')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='openbook_assistant.assistantdocument', verbose_name='Assistant Document')),
            ],
            options={
                'verbose_name': 'Assistant Document Chunk',
                'verbose_name_plural': 'Assistant Document Chunks',
                'ordering': ('parent', 'position'),
            },
        ),
        migrations.AddIndex(
            model_name='assistantdocument',
            index=models.Index(fields=['title', 'file_name'], name='openbook_as_title_bf3fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantdocumentchunk',
            index=models.Index(fields=['parent', 'position'], name='openbook_as_parent__537310_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantdocumentchunk',
            constraint=models.UniqueConstraint(fields=('parent', 'position'), name='openbook_assistant_unique_document_chunk_position'),
        ),
    ]
