# Generated by Django 6.0.5 on 2026-06-15 07:36

import django.db.models.deletion
from django.db import migrations, models

DOCUMENTS_TABLE = "openbook_assistant_documents"


def load_sqlite_vec(sqlite_connection) -> None:
    try:
        import sqlite_vec
    except ImportError as error:
        raise RuntimeError("sqlite-vec is required to run assistant vector migrations.") from error

    sqlite_connection.enable_load_extension(True)
    try:
        sqlite_vec.load(sqlite_connection)
    finally:
        sqlite_connection.enable_load_extension(False)


def rebuild_documents_vector_table(apps, schema_editor) -> None:
    """Rebuild the sqlite-vec index table with course identifiers."""
    if schema_editor.connection.vendor != "sqlite":
        return

    load_sqlite_vec(schema_editor.connection.connection)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP TABLE IF EXISTS {DOCUMENTS_TABLE}")
        cursor.execute(
            f"""
            CREATE VIRTUAL TABLE {DOCUMENTS_TABLE} USING vec0(
                embedding float[1024],
                +course_id TEXT,
                +document_id TEXT,
                +chunk_id TEXT,
                +position INTEGER
            )
            """
        )


def restore_documents_vector_table(apps, schema_editor) -> None:
    """Restore the sqlite-vec index table schema from migration 0003."""
    if schema_editor.connection.vendor != "sqlite":
        return

    load_sqlite_vec(schema_editor.connection.connection)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP TABLE IF EXISTS {DOCUMENTS_TABLE}")
        cursor.execute(
            f"""
            CREATE VIRTUAL TABLE {DOCUMENTS_TABLE} USING vec0(
                embedding float[1024],
                +document_id TEXT,
                +chunk_id TEXT,
                +position INTEGER
            )
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_assistant', '0003_rebuild_documents_vector_table'),
        ('openbook_content', '0005_alter_course_options_alter_librarylink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantdocument',
            options={'ordering': ('course', 'title', 'file_name'), 'verbose_name': 'Assistant Document', 'verbose_name_plural': 'Assistant Documents'},
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Chunk Count'),
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course that owns this assistant document. Empty documents are global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_documents', to='openbook_content.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Embedding Model'),
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='index_error',
            field=models.TextField(blank=True, default='', verbose_name='Index Error'),
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Index Status'),
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Indexed At'),
        ),
        migrations.AddIndex(
            model_name='assistantdocument',
            index=models.Index(fields=['course', 'index_status'], name='openbook_as_course__341efb_idx'),
        ),
        migrations.RunPython(
            rebuild_documents_vector_table,
            reverse_code=restore_documents_vector_table,
        ),
    ]
