# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("openbook_assistant", "0004_alter_assistantdocument_options_and_more"),
        ("openbook_content", "0008_content_anonymous_view_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantdocument",
            name="textbook",
            field=models.ForeignKey(
                blank=True,
                help_text="Textbook this assistant document was generated from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant_documents",
                to="openbook_content.textbook",
                verbose_name="Textbook",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantdocument",
            index=models.Index(
                fields=["textbook", "index_status"],
                name="openbook_as_textboo_9453a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantdocument",
            index=models.Index(
                fields=["course", "textbook", "index_status"],
                name="openbook_as_course__7e7351_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantdocument",
            constraint=models.UniqueConstraint(
                condition=Q(("textbook__isnull", False)),
                fields=("course", "textbook"),
                name="openbook_assistant_unique_course_textbook_document",
            ),
        ),
    ]
