# Generated by Django 6.0.5 on 2026-06-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_assistant', '0005_assistantdocument_textbook'),
        ('openbook_content', '0009_textbookpage_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='openbook_content.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'openbook_assistant_chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('sender', models.CharField(max_length=16, verbose_name='Sender')),
                ('type', models.CharField(default='normal', max_length=16, verbose_name='Type')),
                ('severity', models.CharField(default='info', max_length=16, verbose_name='Severity')),
                ('format', models.CharField(default='markdown', max_length=16, verbose_name='Format')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('guard_rails', models.JSONField(blank=True, default=dict, verbose_name='Guard Rails')),
                ('finished', models.BooleanField(default=True, verbose_name='Finished')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='openbook_assistant.chatsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'openbook_assistant_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'course', '-updated_at'], name='openbook_as_user_id_0c4d9e_idx'),
        ),
    ]
