# Generated by Django 6.0.5 on 2026-06-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_assistant', '0006_chatsession_chatmessage_and_more'),
        ('openbook_content', '0009_textbookpage_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(blank=True, default='Exam', max_length=160, verbose_name='Title')),
                ('exam', models.JSONField(default=dict, verbose_name='Exam')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('total_points', models.IntegerField(default=0, verbose_name='Total Points')),
                ('max_points', models.IntegerField(default=0, verbose_name='Max Points')),
                ('score', models.FloatField(default=0.0, verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='openbook_content.course', verbose_name='Course')),
                ('textbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attempts', to='openbook_content.textbook', verbose_name='Textbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'db_table': 'openbook_assistant_exam_attempt',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'course', '-updated_at'], name='openbook_as_user_id_c7189a_idx')],
            },
        ),
    ]
