# Generated by Django 6.0.5 on 2026-06-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_assistant', '0007_examattempt'),
        ('openbook_content', '0009_textbookpage_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('quiz', models.JSONField(default=dict, verbose_name='Quiz')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Correct Answers')),
                ('question_count', models.IntegerField(default=0, verbose_name='Question Count')),
                ('score', models.FloatField(default=0.0, verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='openbook_content.course', verbose_name='Course')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='openbook_content.textbookpage', verbose_name='Anchor Page')),
                ('textbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='openbook_content.textbook', verbose_name='Textbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'openbook_assistant_quiz_attempt',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'course', '-updated_at'], name='openbook_as_user_id_60c823_idx')],
            },
        ),
    ]
