/*
 * OpenBook: Interactive Online Textbooks - Server
 * (c) 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 */

/**
 * Course exam state backed by the existing course chat WebSocket channel. The exam is
 * generated by the AI and, on submission, graded by the AI (free text) and the server
 * (multiple choice); points and skills are awarded like a quiz result.
 */

import {writable} from "svelte/store";

import {ws} from "../api/client.js";
import type {WebSocketClient, WSConnectionStatus} from "../api/websocket.js";

export type ExamContextSource = "rag_documents" | "course_context";
export type ExamQuestionKind = "free_text" | "multiple_choice";

export interface ExamQuestion {
    id: string;
    kind: ExamQuestionKind;
    prompt: string;
    max_points: number;
    // Option texts for multiple-choice questions; empty for free text.
    options: string[];
}

export interface ExamSource {
    chunk_id: string;
    document_id: string;
    document_title: string;
    position: number;
}

export interface ExamQuestionResult {
    question_id: string;
    kind: ExamQuestionKind;
    prompt: string;
    your_answer: string;
    awarded_points: number;
    max_points: number;
    feedback: string;
    correct: boolean | null;
    correct_answer: string;
}

export interface ExamResult {
    score: number;
    total_points: number;
    max_points: number;
    results: ExamQuestionResult[];
    overall_feedback: string;
    points_awarded: number;
    skills_advanced: string[];
}

/** One submitted answer: free text or the picked option index for multiple choice. */
export interface ExamAnswer {
    question_id: string;
    text?: string;
    selected_index?: number | null;
}

export interface ExamState {
    connection: WSConnectionStatus;
    isLoading: boolean;
    isGrading: boolean;
    errorMessage: string;
    questions: ExamQuestion[];
    contextSource: ExamContextSource | null;
    sources: ExamSource[];
    textbookId: string | null;
    pageId: string | null;
    result: ExamResult | null;
}

interface ExamStart {
    action: "exam_start";
    payload: {
        question_count: number;
        textbook_id?: string;
    };
}

interface ExamSubmit {
    action: "exam_submit";
    payload: {
        answers: ExamAnswer[];
    };
}

interface ExamGenerated {
    action: "exam_generated";
    payload: {
        course_id: string;
        context_source: ExamContextSource;
        questions: ExamQuestion[];
        sources: ExamSource[];
        textbook_id: string | null;
        page_id: string | null;
    };
}

interface ExamGraded {
    action: "exam_graded";
    payload: ExamResult;
}

interface LearningEventStatus {
    action: "learning_event_status";
    payload: {
        event: string;
        success: boolean;
        message: string;
    };
}

/** What the learner earned from a graded exam, passed to {@link ExamStoreOptions.onResultRecorded}. */
export interface ExamRewardSummary {
    pointsAwarded: number;
    skillsAdvanced: string[];
}

type SentMessages = ExamStart | ExamSubmit;
type ReceivedMessages = ExamGenerated | ExamGraded | LearningEventStatus;

type CourseIdSource = string | (() => string | undefined);

export interface ExamStoreOptions {
    /** Called once the backend has graded a submitted exam and awarded points/skills. */
    onResultRecorded?: (reward: ExamRewardSummary) => void;
}

export interface ExamStore {
    subscribe: (run: (value: ExamState) => void) => () => void;
    connect: () => Promise<void>;
    disconnect: () => Promise<void>;
    requestExam: (questionCount?: number, textbookId?: string) => Promise<void>;
    submitExam: (answers: ExamAnswer[]) => Promise<void>;
}

function initialState(): ExamState {
    return {
        connection: "disconnected",
        isLoading: false,
        isGrading: false,
        errorMessage: "",
        questions: [],
        contextSource: null,
        sources: [],
        textbookId: null,
        pageId: null,
        result: null,
    };
}

export function createExamStore(courseId: CourseIdSource, options: ExamStoreOptions = {}): ExamStore {
    const {subscribe, update} = writable<ExamState>(initialState());

    let socket: WebSocketClient<SentMessages, ReceivedMessages> | undefined;

    function resolveCourseId(): string {
        const resolvedCourseId = typeof courseId === "function" ? courseId() : courseId;
        if (!resolvedCourseId) {
            throw new Error("Course id is required for exam generation.");
        }
        return resolvedCourseId;
    }

    async function connect(): Promise<void> {
        if (!socket) {
            const resolvedCourseId = resolveCourseId();
            socket = await ws<SentMessages, ReceivedMessages>(
                `/ai/courses/${encodeURIComponent(resolvedCourseId)}/chat`,
            );

            socket.setConnectionStatusListener((status) => {
                update((state) => ({
                    ...state,
                    connection: status,
                    errorMessage: status === "connected" ? "" : state.errorMessage,
                }));
            });

            socket.setErrorHandler((error) => {
                const message = error instanceof Error ? error.message : "WebSocket error.";
                update((state) => ({...state, errorMessage: message, isLoading: false, isGrading: false}));
            });

            socket.setMessageHandler("exam_generated", (message: ExamGenerated) => {
                update((state) => ({
                    ...state,
                    isLoading: false,
                    errorMessage: "",
                    questions: message.payload.questions,
                    contextSource: message.payload.context_source,
                    sources: message.payload.sources,
                    textbookId: message.payload.textbook_id,
                    pageId: message.payload.page_id,
                    result: null,
                }));
            });

            socket.setMessageHandler("exam_graded", (message: ExamGraded) => {
                update((state) => ({
                    ...state,
                    isGrading: false,
                    errorMessage: "",
                    result: message.payload,
                }));
                options.onResultRecorded?.({
                    pointsAwarded: message.payload.points_awarded ?? 0,
                    skillsAdvanced: message.payload.skills_advanced ?? [],
                });
            });

            socket.setMessageHandler("learning_event_status", (message: LearningEventStatus) => {
                const {event, success, message: detail} = message.payload;
                if (event === "exam_start") {
                    update((state) => ({
                        ...state,
                        isLoading: false,
                        errorMessage: success ? "" : detail,
                    }));
                } else if (event === "exam_submit") {
                    update((state) => ({
                        ...state,
                        isGrading: false,
                        errorMessage: success ? "" : detail,
                    }));
                }
            });
        }

        await socket.connect();
    }

    async function disconnect(): Promise<void> {
        await socket?.disconnect();
    }

    async function requestExam(questionCount = 5, textbookId?: string): Promise<void> {
        update((state) => ({
            ...state,
            isLoading: true,
            isGrading: false,
            errorMessage: "",
            questions: [],
            contextSource: null,
            sources: [],
            textbookId: textbookId ?? null,
            pageId: null,
            result: null,
        }));

        try {
            if (!socket) {
                await connect();
            }
            await socket?.send({
                action: "exam_start",
                payload: {
                    question_count: questionCount,
                    ...(textbookId ? {textbook_id: textbookId} : {}),
                },
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : String(error);
            update((state) => ({...state, isLoading: false, errorMessage: message}));
        }
    }

    async function submitExam(answers: ExamAnswer[]): Promise<void> {
        update((state) => ({...state, isGrading: true, errorMessage: ""}));

        try {
            // The socket may have gone idle while the learner worked through the exam;
            // reconnect (a no-op when already connected) so the submission is delivered.
            await connect();
            await socket?.send({
                action: "exam_submit",
                payload: {answers},
            });
        } catch (error) {
            const message = error instanceof Error ? error.message : String(error);
            update((state) => ({...state, isGrading: false, errorMessage: message}));
        }
    }

    return {
        subscribe,
        connect,
        disconnect,
        requestExam,
        submitExam,
    };
}
