# OpenBook: Interactive Online Textbooks - Server
# © 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
# Ledejna Salihi (@LedejnaSalihi)
# Lars Zieger (@lzieger03)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Generated by Django 6.0.5 on 2026-06-09 11:42

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "openbook_content",
            "0005_alter_course_options_alter_librarylink_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textbookpage",
            options={
                "ordering": ("textbook_id", "parent_id", "position", "name"),
                "verbose_name": "Textbook Page",
                "verbose_name_plural": "Textbook Pages",
            },
        ),
    ]
