# Generated by Django 6.0.5 on 2026-06-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_content', '0005_alter_course_options_alter_librarylink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbookpage',
            options={'ordering': ('textbook_id', 'parent_id', 'position', 'name'), 'verbose_name': 'Textbook Page', 'verbose_name_plural': 'Textbook Pages'},
        ),
    ]
