<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-06-15 07:36
=======
# Generated by Django 6.0.5 on 2026-06-09 11:42

from __future__ import annotations
>>>>>>> origin/frontend-ai-integration-test

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('openbook_content', '0005_alter_course_options_alter_librarylink_options_and_more'),
=======
        (
            "openbook_content",
            "0005_alter_course_options_alter_librarylink_options_and_more",
        ),
>>>>>>> origin/frontend-ai-integration-test
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='textbookpage',
            options={'ordering': ('textbook_id', 'parent_id', 'position', 'name'), 'verbose_name': 'Textbook Page', 'verbose_name_plural': 'Textbook Pages'},
=======
            name="textbookpage",
            options={
                "ordering": ("textbook_id", "parent_id", "position", "name"),
                "verbose_name": "Textbook Page",
                "verbose_name_plural": "Textbook Pages",
            },
>>>>>>> origin/frontend-ai-integration-test
        ),
    ]
