# Generated by Django 6.0.5 on 2026-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_content', '0006_alter_textbookpage_options'),
        ('openbook_gamification', '0010_skillprogress_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills that learners train and level up by working in this course.', related_name='courses', to='openbook_gamification.skill', verbose_name='Skills'),
        ),
    ]
