# OpenBook: Interactive Online Textbooks - Server
# © 2026 Dennis Schulmeister-Zimolong <dennis@wpvs.de>
# Ledejna Salihi (@LedejnaSalihi)
# Lars Zieger (@lzieger03)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Generated by Django 6.0.5 on 2026-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_content', '0006_alter_textbookpage_options'),
        ('openbook_gamification', '0010_skillprogress_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills that learners train and level up by working in this course.', related_name='courses', to='openbook_gamification.skill', verbose_name='Skills'),
        ),
    ]
