/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountProgressMe
 */
export interface AccountProgressMe {
    /**
     * 
     * @type {number}
     * @memberof AccountProgressMe
     */
    pointTotal: number;
    /**
     * 
     * @type {number}
     * @memberof AccountProgressMe
     */
    level: number;
    /**
     * 
     * @type {number}
     * @memberof AccountProgressMe
     */
    currentLevelMinPoints: number;
    /**
     * 
     * @type {number}
     * @memberof AccountProgressMe
     */
    nextLevelMinPoints: number | null;
}

/**
 * Check if a given object implements the AccountProgressMe interface.
 */
export function instanceOfAccountProgressMe(value: object): value is AccountProgressMe {
    if (!('pointTotal' in value) || value['pointTotal'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('currentLevelMinPoints' in value) || value['currentLevelMinPoints'] === undefined) return false;
    if (!('nextLevelMinPoints' in value) || value['nextLevelMinPoints'] === undefined) return false;
    return true;
}

export function AccountProgressMeFromJSON(json: any): AccountProgressMe {
    return AccountProgressMeFromJSONTyped(json, false);
}

export function AccountProgressMeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountProgressMe {
    if (json == null) {
        return json;
    }
    return {
        
        'pointTotal': json['point_total'],
        'level': json['level'],
        'currentLevelMinPoints': json['current_level_min_points'],
        'nextLevelMinPoints': json['next_level_min_points'],
    };
}

export function AccountProgressMeToJSON(json: any): AccountProgressMe {
    return AccountProgressMeToJSONTyped(json, false);
}

export function AccountProgressMeToJSONTyped(value?: AccountProgressMe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'point_total': value['pointTotal'],
        'level': value['level'],
        'current_level_min_points': value['currentLevelMinPoints'],
        'next_level_min_points': value['nextLevelMinPoints'],
    };
}

