/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Account Progress
 * @export
 * @interface AccountProgress
 */
export interface AccountProgress {
    /**
     * 
     * @type {string}
     * @memberof AccountProgress
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof AccountProgress
     */
    account: string;
    /**
     * 
     * @type {number}
     * @memberof AccountProgress
     */
    pointTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountProgress
     */
    level?: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountProgress
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the AccountProgress interface.
 */
export function instanceOfAccountProgress(value: object): value is AccountProgress {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AccountProgressFromJSON(json: any): AccountProgress {
    return AccountProgressFromJSONTyped(json, false);
}

export function AccountProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'account': json['account'],
        'pointTotal': json['point_total'] == null ? undefined : json['point_total'],
        'level': json['level'] == null ? undefined : json['level'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function AccountProgressToJSON(json: any): AccountProgress {
    return AccountProgressToJSONTyped(json, false);
}

export function AccountProgressToJSONTyped(value?: Omit<AccountProgress, 'id'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'point_total': value['pointTotal'],
        'level': value['level'],
    };
}

