/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Account Points
 * @export
 * @interface AccountPoints
 */
export interface AccountPoints {
    /**
     * 
     * @type {string}
     * @memberof AccountPoints
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof AccountPoints
     */
    account: string;
    /**
     * 
     * @type {number}
     * @memberof AccountPoints
     */
    pointTotal?: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountPoints
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the AccountPoints interface.
 */
export function instanceOfAccountPoints(value: object): value is AccountPoints {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AccountPointsFromJSON(json: any): AccountPoints {
    return AccountPointsFromJSONTyped(json, false);
}

export function AccountPointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountPoints {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'account': json['account'],
        'pointTotal': json['point_total'] == null ? undefined : json['point_total'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function AccountPointsToJSON(json: any): AccountPoints {
    return AccountPointsToJSONTyped(json, false);
}

export function AccountPointsToJSONTyped(value?: Omit<AccountPoints, 'id'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'point_total': value['pointTotal'],
    };
}

