/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllowedPermission
 */
export interface AllowedPermission {
    /**
     * 
     * @type {number}
     * @memberof AllowedPermission
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AllowedPermission
     */
    perm: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedPermission
     */
    app: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedPermission
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof AllowedPermission
     */
    name: string;
}

/**
 * Check if a given object implements the AllowedPermission interface.
 */
export function instanceOfAllowedPermission(value: object): value is AllowedPermission {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('perm' in value) || value['perm'] === undefined) return false;
    if (!('app' in value) || value['app'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AllowedPermissionFromJSON(json: any): AllowedPermission {
    return AllowedPermissionFromJSONTyped(json, false);
}

export function AllowedPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllowedPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'perm': json['perm'],
        'app': json['app'],
        'model': json['model'],
        'name': json['name'],
    };
}

export function AllowedPermissionToJSON(json: any): AllowedPermission {
    return AllowedPermissionToJSONTyped(json, false);
}

export function AllowedPermissionToJSONTyped(value?: AllowedPermission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'perm': value['perm'],
        'app': value['app'],
        'model': value['model'],
        'name': value['name'],
    };
}

