/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `manual` - Manual Assignment
 * * `self-enrollment` - Self-Enrollment
 * * `access-request` - Access Request
 * @export
 */
export const AssignmentMethodEnum = {
    Manual: 'manual',
    SelfEnrollment: 'self-enrollment',
    AccessRequest: 'access-request'
} as const;
export type AssignmentMethodEnum = typeof AssignmentMethodEnum[keyof typeof AssignmentMethodEnum];


export function instanceOfAssignmentMethodEnum(value: any): boolean {
    for (const key in AssignmentMethodEnum) {
        if (Object.prototype.hasOwnProperty.call(AssignmentMethodEnum, key)) {
            if (AssignmentMethodEnum[key as keyof typeof AssignmentMethodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AssignmentMethodEnumFromJSON(json: any): AssignmentMethodEnum {
    return AssignmentMethodEnumFromJSONTyped(json, false);
}

export function AssignmentMethodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentMethodEnum {
    return json as AssignmentMethodEnum;
}

export function AssignmentMethodEnumToJSON(value?: AssignmentMethodEnum | null): any {
    return value as any;
}

export function AssignmentMethodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AssignmentMethodEnum {
    return value as AssignmentMethodEnum;
}

