/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Authentication Token
 * @export
 * @interface AuthTokenUpdate
 */
export interface AuthTokenUpdate {
    /**
     * 
     * @type {string}
     * @memberof AuthTokenUpdate
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokenUpdate
     */
    readonly user: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokenUpdate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokenUpdate
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof AuthTokenUpdate
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AuthTokenUpdate
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AuthTokenUpdate
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthTokenUpdate
     */
    endDate?: Date | null;
}



/**
 * Check if a given object implements the AuthTokenUpdate interface.
 */
export function instanceOfAuthTokenUpdate(value: object): value is AuthTokenUpdate {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthTokenUpdateFromJSON(json: any): AuthTokenUpdate {
    return AuthTokenUpdateFromJSONTyped(json, false);
}

export function AuthTokenUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokenUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
    };
}

export function AuthTokenUpdateToJSON(json: any): AuthTokenUpdate {
    return AuthTokenUpdateToJSONTyped(json, false);
}

export function AuthTokenUpdateToJSONTyped(value?: Omit<AuthTokenUpdate, 'id'|'user'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'is_active': value['isActive'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

