/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Authentication Token
 * @export
 * @interface AuthToken
 */
export interface AuthToken {
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    readonly token: string;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof AuthToken
     */
    textFormat?: TextFormatEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AuthToken
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AuthToken
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthToken
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof AuthToken
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AuthToken
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof AuthToken
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the AuthToken interface.
 */
export function instanceOfAuthToken(value: object): value is AuthToken {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function AuthTokenFromJSON(json: any): AuthToken {
    return AuthTokenFromJSONTyped(json, false);
}

export function AuthTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthToken {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': json['user'],
        'token': json['token'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function AuthTokenToJSON(json: any): AuthToken {
    return AuthTokenToJSONTyped(json, false);
}

export function AuthTokenToJSONTyped(value?: Omit<AuthToken, 'id'|'token'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'is_active': value['isActive'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

