/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `minutes` - Minutes
 * * `hours` - Hours
 * * `days` - Days
 * * `weeks` - Weeks
 * * `months` - Months
 * * `years` - Years
 * @export
 */
export const DurationPeriodEnum = {
    Minutes: 'minutes',
    Hours: 'hours',
    Days: 'days',
    Weeks: 'weeks',
    Months: 'months',
    Years: 'years'
} as const;
export type DurationPeriodEnum = typeof DurationPeriodEnum[keyof typeof DurationPeriodEnum];


export function instanceOfDurationPeriodEnum(value: any): boolean {
    for (const key in DurationPeriodEnum) {
        if (Object.prototype.hasOwnProperty.call(DurationPeriodEnum, key)) {
            if (DurationPeriodEnum[key as keyof typeof DurationPeriodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DurationPeriodEnumFromJSON(json: any): DurationPeriodEnum {
    return DurationPeriodEnumFromJSONTyped(json, false);
}

export function DurationPeriodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DurationPeriodEnum {
    return json as DurationPeriodEnum;
}

export function DurationPeriodEnumToJSON(value?: DurationPeriodEnum | null): any {
    return value as any;
}

export function DurationPeriodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): DurationPeriodEnum {
    return value as DurationPeriodEnum;
}

