/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrollActionRequest
 */
export interface EnrollActionRequest {
    /**
     * 
     * @type {string}
     * @memberof EnrollActionRequest
     */
    passphrase?: string;
}

/**
 * Check if a given object implements the EnrollActionRequest interface.
 */
export function instanceOfEnrollActionRequest(value: object): value is EnrollActionRequest {
    return true;
}

export function EnrollActionRequestFromJSON(json: any): EnrollActionRequest {
    return EnrollActionRequestFromJSONTyped(json, false);
}

export function EnrollActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollActionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'passphrase': json['passphrase'] == null ? undefined : json['passphrase'],
    };
}

export function EnrollActionRequestToJSON(json: any): EnrollActionRequest {
    return EnrollActionRequestToJSONTyped(json, false);
}

export function EnrollActionRequestToJSONTyped(value?: EnrollActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passphrase': value['passphrase'],
    };
}

