/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTML Library Version
 * @export
 * @interface HTMLLibraryVersion
 */
export interface HTMLLibraryVersion {
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    parent: string;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    version: string;
    /**
     * 
     * @type {any}
     * @memberof HTMLLibraryVersion
     */
    dependencies?: any | null;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    readonly frontendUrl: string;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    fileData?: string;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    fileName?: string;
    /**
     * 
     * @type {number}
     * @memberof HTMLLibraryVersion
     */
    fileSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    mimeType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof HTMLLibraryVersion
     */
    readonly components: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof HTMLLibraryVersion
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof HTMLLibraryVersion
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof HTMLLibraryVersion
     */
    readonly modifiedAt: Date | null;
}

/**
 * Check if a given object implements the HTMLLibraryVersion interface.
 */
export function instanceOfHTMLLibraryVersion(value: object): value is HTMLLibraryVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('parent' in value) || value['parent'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('frontendUrl' in value) || value['frontendUrl'] === undefined) return false;
    if (!('components' in value) || value['components'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function HTMLLibraryVersionFromJSON(json: any): HTMLLibraryVersion {
    return HTMLLibraryVersionFromJSONTyped(json, false);
}

export function HTMLLibraryVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTMLLibraryVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parent': json['parent'],
        'version': json['version'],
        'dependencies': json['dependencies'] == null ? undefined : json['dependencies'],
        'frontendUrl': json['frontend_url'],
        'fileData': json['file_data'] == null ? undefined : json['file_data'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'fileSize': json['file_size'] == null ? undefined : json['file_size'],
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'components': json['components'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function HTMLLibraryVersionToJSON(json: any): HTMLLibraryVersion {
    return HTMLLibraryVersionToJSONTyped(json, false);
}

export function HTMLLibraryVersionToJSONTyped(value?: Omit<HTMLLibraryVersion, 'id'|'frontend_url'|'components'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parent': value['parent'],
        'version': value['version'],
        'dependencies': value['dependencies'],
        'file_data': value['fileData'],
        'file_name': value['fileName'],
        'file_size': value['fileSize'],
        'mime_type': value['mimeType'],
    };
}

