/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RewardEvent } from './RewardEvent';
import {
    RewardEventFromJSON,
    RewardEventFromJSONTyped,
    RewardEventToJSON,
    RewardEventToJSONTyped,
} from './RewardEvent';

/**
 * 
 * @export
 * @interface PaginatedRewardEventList
 */
export interface PaginatedRewardEventList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRewardEventList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRewardEventList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRewardEventList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RewardEvent>}
     * @memberof PaginatedRewardEventList
     */
    results: Array<RewardEvent>;
}

/**
 * Check if a given object implements the PaginatedRewardEventList interface.
 */
export function instanceOfPaginatedRewardEventList(value: object): value is PaginatedRewardEventList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRewardEventListFromJSON(json: any): PaginatedRewardEventList {
    return PaginatedRewardEventListFromJSONTyped(json, false);
}

export function PaginatedRewardEventListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRewardEventList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RewardEventFromJSON)),
    };
}

export function PaginatedRewardEventListToJSON(json: any): PaginatedRewardEventList {
    return PaginatedRewardEventListToJSONTyped(json, false);
}

export function PaginatedRewardEventListToJSONTyped(value?: PaginatedRewardEventList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RewardEventToJSON)),
    };
}

