/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountPoints } from './AccountPoints';
import {
    AccountPointsFromJSON,
    AccountPointsFromJSONTyped,
    AccountPointsToJSON,
    AccountPointsToJSONTyped,
} from './AccountPoints';

/**
 * 
 * @export
 * @interface PaginatedAccountPointsList
 */
export interface PaginatedAccountPointsList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAccountPointsList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccountPointsList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccountPointsList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AccountPoints>}
     * @memberof PaginatedAccountPointsList
     */
    results: Array<AccountPoints>;
}

/**
 * Check if a given object implements the PaginatedAccountPointsList interface.
 */
export function instanceOfPaginatedAccountPointsList(value: object): value is PaginatedAccountPointsList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAccountPointsListFromJSON(json: any): PaginatedAccountPointsList {
    return PaginatedAccountPointsListFromJSONTyped(json, false);
}

export function PaginatedAccountPointsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAccountPointsList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AccountPointsFromJSON)),
    };
}

export function PaginatedAccountPointsListToJSON(json: any): PaginatedAccountPointsList {
    return PaginatedAccountPointsListToJSONTyped(json, false);
}

export function PaginatedAccountPointsListToJSONTyped(value?: PaginatedAccountPointsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AccountPointsToJSON)),
    };
}

