/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseProgress } from './CourseProgress';
import {
    CourseProgressFromJSON,
    CourseProgressFromJSONTyped,
    CourseProgressToJSON,
    CourseProgressToJSONTyped,
} from './CourseProgress';

/**
 * 
 * @export
 * @interface PaginatedCourseProgressList
 */
export interface PaginatedCourseProgressList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCourseProgressList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseProgressList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCourseProgressList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CourseProgress>}
     * @memberof PaginatedCourseProgressList
     */
    results: Array<CourseProgress>;
}

/**
 * Check if a given object implements the PaginatedCourseProgressList interface.
 */
export function instanceOfPaginatedCourseProgressList(value: object): value is PaginatedCourseProgressList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCourseProgressListFromJSON(json: any): PaginatedCourseProgressList {
    return PaginatedCourseProgressListFromJSONTyped(json, false);
}

export function PaginatedCourseProgressListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCourseProgressList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CourseProgressFromJSON)),
    };
}

export function PaginatedCourseProgressListToJSON(json: any): PaginatedCourseProgressList {
    return PaginatedCourseProgressListToJSONTyped(json, false);
}

export function PaginatedCourseProgressListToJSONTyped(value?: PaginatedCourseProgressList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CourseProgressToJSON)),
    };
}

