/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SkillProgress } from './SkillProgress';
import {
    SkillProgressFromJSON,
    SkillProgressFromJSONTyped,
    SkillProgressToJSON,
    SkillProgressToJSONTyped,
} from './SkillProgress';

/**
 * 
 * @export
 * @interface PaginatedSkillProgressList
 */
export interface PaginatedSkillProgressList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSkillProgressList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSkillProgressList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSkillProgressList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SkillProgress>}
     * @memberof PaginatedSkillProgressList
     */
    results: Array<SkillProgress>;
}

/**
 * Check if a given object implements the PaginatedSkillProgressList interface.
 */
export function instanceOfPaginatedSkillProgressList(value: object): value is PaginatedSkillProgressList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSkillProgressListFromJSON(json: any): PaginatedSkillProgressList {
    return PaginatedSkillProgressListFromJSONTyped(json, false);
}

export function PaginatedSkillProgressListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSkillProgressList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SkillProgressFromJSON)),
    };
}

export function PaginatedSkillProgressListToJSON(json: any): PaginatedSkillProgressList {
    return PaginatedSkillProgressListToJSONTyped(json, false);
}

export function PaginatedSkillProgressListToJSONTyped(value?: PaginatedSkillProgressList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SkillProgressToJSON)),
    };
}

