/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrollmentMethod } from './EnrollmentMethod';
import {
    EnrollmentMethodFromJSON,
    EnrollmentMethodFromJSONTyped,
    EnrollmentMethodToJSON,
    EnrollmentMethodToJSONTyped,
} from './EnrollmentMethod';

/**
 * 
 * @export
 * @interface PaginatedEnrollmentMethodList
 */
export interface PaginatedEnrollmentMethodList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEnrollmentMethodList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEnrollmentMethodList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEnrollmentMethodList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<EnrollmentMethod>}
     * @memberof PaginatedEnrollmentMethodList
     */
    results: Array<EnrollmentMethod>;
}

/**
 * Check if a given object implements the PaginatedEnrollmentMethodList interface.
 */
export function instanceOfPaginatedEnrollmentMethodList(value: object): value is PaginatedEnrollmentMethodList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedEnrollmentMethodListFromJSON(json: any): PaginatedEnrollmentMethodList {
    return PaginatedEnrollmentMethodListFromJSONTyped(json, false);
}

export function PaginatedEnrollmentMethodListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEnrollmentMethodList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(EnrollmentMethodFromJSON)),
    };
}

export function PaginatedEnrollmentMethodListToJSON(json: any): PaginatedEnrollmentMethodList {
    return PaginatedEnrollmentMethodListToJSONTyped(json, false);
}

export function PaginatedEnrollmentMethodListToJSONTyped(value?: PaginatedEnrollmentMethodList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(EnrollmentMethodToJSON)),
    };
}

