/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllowedRolePermission } from './AllowedRolePermission';
import {
    AllowedRolePermissionFromJSON,
    AllowedRolePermissionFromJSONTyped,
    AllowedRolePermissionToJSON,
    AllowedRolePermissionToJSONTyped,
} from './AllowedRolePermission';

/**
 * 
 * @export
 * @interface PaginatedAllowedRolePermissionList
 */
export interface PaginatedAllowedRolePermissionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAllowedRolePermissionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAllowedRolePermissionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAllowedRolePermissionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AllowedRolePermission>}
     * @memberof PaginatedAllowedRolePermissionList
     */
    results: Array<AllowedRolePermission>;
}

/**
 * Check if a given object implements the PaginatedAllowedRolePermissionList interface.
 */
export function instanceOfPaginatedAllowedRolePermissionList(value: object): value is PaginatedAllowedRolePermissionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAllowedRolePermissionListFromJSON(json: any): PaginatedAllowedRolePermissionList {
    return PaginatedAllowedRolePermissionListFromJSONTyped(json, false);
}

export function PaginatedAllowedRolePermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAllowedRolePermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AllowedRolePermissionFromJSON)),
    };
}

export function PaginatedAllowedRolePermissionListToJSON(json: any): PaginatedAllowedRolePermissionList {
    return PaginatedAllowedRolePermissionListToJSONTyped(json, false);
}

export function PaginatedAllowedRolePermissionListToJSONTyped(value?: PaginatedAllowedRolePermissionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AllowedRolePermissionToJSON)),
    };
}

