/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleAssignment } from './RoleAssignment';
import {
    RoleAssignmentFromJSON,
    RoleAssignmentFromJSONTyped,
    RoleAssignmentToJSON,
    RoleAssignmentToJSONTyped,
} from './RoleAssignment';

/**
 * 
 * @export
 * @interface PaginatedRoleAssignmentList
 */
export interface PaginatedRoleAssignmentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRoleAssignmentList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRoleAssignmentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRoleAssignmentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RoleAssignment>}
     * @memberof PaginatedRoleAssignmentList
     */
    results: Array<RoleAssignment>;
}

/**
 * Check if a given object implements the PaginatedRoleAssignmentList interface.
 */
export function instanceOfPaginatedRoleAssignmentList(value: object): value is PaginatedRoleAssignmentList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRoleAssignmentListFromJSON(json: any): PaginatedRoleAssignmentList {
    return PaginatedRoleAssignmentListFromJSONTyped(json, false);
}

export function PaginatedRoleAssignmentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRoleAssignmentList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RoleAssignmentFromJSON)),
    };
}

export function PaginatedRoleAssignmentListToJSON(json: any): PaginatedRoleAssignmentList {
    return PaginatedRoleAssignmentListToJSONTyped(json, false);
}

export function PaginatedRoleAssignmentListToJSONTyped(value?: PaginatedRoleAssignmentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RoleAssignmentToJSON)),
    };
}

