/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentUser } from './CurrentUser';
import {
    CurrentUserFromJSON,
    CurrentUserFromJSONTyped,
    CurrentUserToJSON,
    CurrentUserToJSONTyped,
} from './CurrentUser';

/**
 * 
 * @export
 * @interface PaginatedCurrentUserList
 */
export interface PaginatedCurrentUserList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCurrentUserList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCurrentUserList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCurrentUserList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CurrentUser>}
     * @memberof PaginatedCurrentUserList
     */
    results: Array<CurrentUser>;
}

/**
 * Check if a given object implements the PaginatedCurrentUserList interface.
 */
export function instanceOfPaginatedCurrentUserList(value: object): value is PaginatedCurrentUserList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedCurrentUserListFromJSON(json: any): PaginatedCurrentUserList {
    return PaginatedCurrentUserListFromJSONTyped(json, false);
}

export function PaginatedCurrentUserListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCurrentUserList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CurrentUserFromJSON)),
    };
}

export function PaginatedCurrentUserListToJSON(json: any): PaginatedCurrentUserList {
    return PaginatedCurrentUserListToJSONTyped(json, false);
}

export function PaginatedCurrentUserListToJSONTyped(value?: PaginatedCurrentUserList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CurrentUserToJSON)),
    };
}

