/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthToken } from './AuthToken';
import {
    AuthTokenFromJSON,
    AuthTokenFromJSONTyped,
    AuthTokenToJSON,
    AuthTokenToJSONTyped,
} from './AuthToken';

/**
 * 
 * @export
 * @interface PaginatedAuthTokenList
 */
export interface PaginatedAuthTokenList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuthTokenList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuthTokenList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuthTokenList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AuthToken>}
     * @memberof PaginatedAuthTokenList
     */
    results: Array<AuthToken>;
}

/**
 * Check if a given object implements the PaginatedAuthTokenList interface.
 */
export function instanceOfPaginatedAuthTokenList(value: object): value is PaginatedAuthTokenList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAuthTokenListFromJSON(json: any): PaginatedAuthTokenList {
    return PaginatedAuthTokenListFromJSONTyped(json, false);
}

export function PaginatedAuthTokenListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAuthTokenList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AuthTokenFromJSON)),
    };
}

export function PaginatedAuthTokenListToJSON(json: any): PaginatedAuthTokenList {
    return PaginatedAuthTokenListToJSONTyped(json, false);
}

export function PaginatedAuthTokenListToJSONTyped(value?: PaginatedAuthTokenList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AuthTokenToJSON)),
    };
}

