/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Skill } from './Skill';
import {
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
    SkillToJSONTyped,
} from './Skill';

/**
 * 
 * @export
 * @interface PaginatedSkillList
 */
export interface PaginatedSkillList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSkillList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSkillList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSkillList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Skill>}
     * @memberof PaginatedSkillList
     */
    results: Array<Skill>;
}

/**
 * Check if a given object implements the PaginatedSkillList interface.
 */
export function instanceOfPaginatedSkillList(value: object): value is PaginatedSkillList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSkillListFromJSON(json: any): PaginatedSkillList {
    return PaginatedSkillListFromJSONTyped(json, false);
}

export function PaginatedSkillListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSkillList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SkillFromJSON)),
    };
}

export function PaginatedSkillListToJSON(json: any): PaginatedSkillList {
    return PaginatedSkillListToJSONTyped(json, false);
}

export function PaginatedSkillListToJSONTyped(value?: PaginatedSkillList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SkillToJSON)),
    };
}

