/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTMLLibraryVersion } from './HTMLLibraryVersion';
import {
    HTMLLibraryVersionFromJSON,
    HTMLLibraryVersionFromJSONTyped,
    HTMLLibraryVersionToJSON,
    HTMLLibraryVersionToJSONTyped,
} from './HTMLLibraryVersion';

/**
 * 
 * @export
 * @interface PaginatedHTMLLibraryVersionList
 */
export interface PaginatedHTMLLibraryVersionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedHTMLLibraryVersionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHTMLLibraryVersionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHTMLLibraryVersionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<HTMLLibraryVersion>}
     * @memberof PaginatedHTMLLibraryVersionList
     */
    results: Array<HTMLLibraryVersion>;
}

/**
 * Check if a given object implements the PaginatedHTMLLibraryVersionList interface.
 */
export function instanceOfPaginatedHTMLLibraryVersionList(value: object): value is PaginatedHTMLLibraryVersionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedHTMLLibraryVersionListFromJSON(json: any): PaginatedHTMLLibraryVersionList {
    return PaginatedHTMLLibraryVersionListFromJSONTyped(json, false);
}

export function PaginatedHTMLLibraryVersionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedHTMLLibraryVersionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(HTMLLibraryVersionFromJSON)),
    };
}

export function PaginatedHTMLLibraryVersionListToJSON(json: any): PaginatedHTMLLibraryVersionList {
    return PaginatedHTMLLibraryVersionListToJSONTyped(json, false);
}

export function PaginatedHTMLLibraryVersionListToJSONTyped(value?: PaginatedHTMLLibraryVersionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(HTMLLibraryVersionToJSON)),
    };
}

