/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';

/**
 * 
 * @export
 * @interface PaginatedRoleList
 */
export interface PaginatedRoleList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRoleList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRoleList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRoleList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Role>}
     * @memberof PaginatedRoleList
     */
    results: Array<Role>;
}

/**
 * Check if a given object implements the PaginatedRoleList interface.
 */
export function instanceOfPaginatedRoleList(value: object): value is PaginatedRoleList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRoleListFromJSON(json: any): PaginatedRoleList {
    return PaginatedRoleListFromJSONTyped(json, false);
}

export function PaginatedRoleListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRoleList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RoleFromJSON)),
    };
}

export function PaginatedRoleListToJSON(json: any): PaginatedRoleList {
    return PaginatedRoleListToJSONTyped(json, false);
}

export function PaginatedRoleListToJSONTyped(value?: PaginatedRoleList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RoleToJSON)),
    };
}

