/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTMLComponentDefinition } from './HTMLComponentDefinition';
import {
    HTMLComponentDefinitionFromJSON,
    HTMLComponentDefinitionFromJSONTyped,
    HTMLComponentDefinitionToJSON,
    HTMLComponentDefinitionToJSONTyped,
} from './HTMLComponentDefinition';

/**
 * 
 * @export
 * @interface PaginatedHTMLComponentDefinitionList
 */
export interface PaginatedHTMLComponentDefinitionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedHTMLComponentDefinitionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHTMLComponentDefinitionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHTMLComponentDefinitionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<HTMLComponentDefinition>}
     * @memberof PaginatedHTMLComponentDefinitionList
     */
    results: Array<HTMLComponentDefinition>;
}

/**
 * Check if a given object implements the PaginatedHTMLComponentDefinitionList interface.
 */
export function instanceOfPaginatedHTMLComponentDefinitionList(value: object): value is PaginatedHTMLComponentDefinitionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedHTMLComponentDefinitionListFromJSON(json: any): PaginatedHTMLComponentDefinitionList {
    return PaginatedHTMLComponentDefinitionListFromJSONTyped(json, false);
}

export function PaginatedHTMLComponentDefinitionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedHTMLComponentDefinitionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(HTMLComponentDefinitionFromJSON)),
    };
}

export function PaginatedHTMLComponentDefinitionListToJSON(json: any): PaginatedHTMLComponentDefinitionList {
    return PaginatedHTMLComponentDefinitionListToJSONTyped(json, false);
}

export function PaginatedHTMLComponentDefinitionListToJSONTyped(value?: PaginatedHTMLComponentDefinitionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(HTMLComponentDefinitionToJSON)),
    };
}

