/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * 
 * @export
 * @interface PaginatedPermissionList
 */
export interface PaginatedPermissionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPermissionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPermissionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPermissionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Permission>}
     * @memberof PaginatedPermissionList
     */
    results: Array<Permission>;
}

/**
 * Check if a given object implements the PaginatedPermissionList interface.
 */
export function instanceOfPaginatedPermissionList(value: object): value is PaginatedPermissionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedPermissionListFromJSON(json: any): PaginatedPermissionList {
    return PaginatedPermissionListFromJSONTyped(json, false);
}

export function PaginatedPermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(PermissionFromJSON)),
    };
}

export function PaginatedPermissionListToJSON(json: any): PaginatedPermissionList {
    return PaginatedPermissionListToJSONTyped(json, false);
}

export function PaginatedPermissionListToJSONTyped(value?: PaginatedPermissionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(PermissionToJSON)),
    };
}

