/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTMLLibraryText } from './HTMLLibraryText';
import {
    HTMLLibraryTextFromJSON,
    HTMLLibraryTextFromJSONTyped,
    HTMLLibraryTextToJSON,
    HTMLLibraryTextToJSONTyped,
} from './HTMLLibraryText';

/**
 * 
 * @export
 * @interface PaginatedHTMLLibraryTextList
 */
export interface PaginatedHTMLLibraryTextList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedHTMLLibraryTextList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHTMLLibraryTextList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHTMLLibraryTextList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<HTMLLibraryText>}
     * @memberof PaginatedHTMLLibraryTextList
     */
    results: Array<HTMLLibraryText>;
}

/**
 * Check if a given object implements the PaginatedHTMLLibraryTextList interface.
 */
export function instanceOfPaginatedHTMLLibraryTextList(value: object): value is PaginatedHTMLLibraryTextList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedHTMLLibraryTextListFromJSON(json: any): PaginatedHTMLLibraryTextList {
    return PaginatedHTMLLibraryTextListFromJSONTyped(json, false);
}

export function PaginatedHTMLLibraryTextListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedHTMLLibraryTextList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(HTMLLibraryTextFromJSON)),
    };
}

export function PaginatedHTMLLibraryTextListToJSON(json: any): PaginatedHTMLLibraryTextList {
    return PaginatedHTMLLibraryTextListToJSONTyped(json, false);
}

export function PaginatedHTMLLibraryTextListToJSONTyped(value?: PaginatedHTMLLibraryTextList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(HTMLLibraryTextToJSON)),
    };
}

