/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reward } from './Reward';
import {
    RewardFromJSON,
    RewardFromJSONTyped,
    RewardToJSON,
    RewardToJSONTyped,
} from './Reward';

/**
 * 
 * @export
 * @interface PaginatedRewardList
 */
export interface PaginatedRewardList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRewardList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRewardList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRewardList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Reward>}
     * @memberof PaginatedRewardList
     */
    results: Array<Reward>;
}

/**
 * Check if a given object implements the PaginatedRewardList interface.
 */
export function instanceOfPaginatedRewardList(value: object): value is PaginatedRewardList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRewardListFromJSON(json: any): PaginatedRewardList {
    return PaginatedRewardListFromJSONTyped(json, false);
}

export function PaginatedRewardListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRewardList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RewardFromJSON)),
    };
}

export function PaginatedRewardListToJSON(json: any): PaginatedRewardList {
    return PaginatedRewardListToJSONTyped(json, false);
}

export function PaginatedRewardListToJSONTyped(value?: PaginatedRewardList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RewardToJSON)),
    };
}

