/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaFile } from './MediaFile';
import {
    MediaFileFromJSON,
    MediaFileFromJSONTyped,
    MediaFileToJSON,
    MediaFileToJSONTyped,
} from './MediaFile';

/**
 * 
 * @export
 * @interface PaginatedMediaFileList
 */
export interface PaginatedMediaFileList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMediaFileList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMediaFileList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMediaFileList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<MediaFile>}
     * @memberof PaginatedMediaFileList
     */
    results: Array<MediaFile>;
}

/**
 * Check if a given object implements the PaginatedMediaFileList interface.
 */
export function instanceOfPaginatedMediaFileList(value: object): value is PaginatedMediaFileList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedMediaFileListFromJSON(json: any): PaginatedMediaFileList {
    return PaginatedMediaFileListFromJSONTyped(json, false);
}

export function PaginatedMediaFileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMediaFileList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(MediaFileFromJSON)),
    };
}

export function PaginatedMediaFileListToJSON(json: any): PaginatedMediaFileList {
    return PaginatedMediaFileListToJSONTyped(json, false);
}

export function PaginatedMediaFileListToJSONTyped(value?: PaginatedMediaFileList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(MediaFileToJSON)),
    };
}

