/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';

/**
 * 
 * @export
 * @interface PaginatedLanguageList
 */
export interface PaginatedLanguageList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLanguageList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLanguageList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLanguageList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Language>}
     * @memberof PaginatedLanguageList
     */
    results: Array<Language>;
}

/**
 * Check if a given object implements the PaginatedLanguageList interface.
 */
export function instanceOfPaginatedLanguageList(value: object): value is PaginatedLanguageList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedLanguageListFromJSON(json: any): PaginatedLanguageList {
    return PaginatedLanguageListFromJSONTyped(json, false);
}

export function PaginatedLanguageListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLanguageList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LanguageFromJSON)),
    };
}

export function PaginatedLanguageListToJSON(json: any): PaginatedLanguageList {
    return PaginatedLanguageListToJSONTyped(json, false);
}

export function PaginatedLanguageListToJSONTyped(value?: PaginatedLanguageList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(LanguageToJSON)),
    };
}

