/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Media File
 * @export
 * @interface PatchedMediaFile
 */
export interface PatchedMediaFile {
    /**
     * 
     * @type {number}
     * @memberof PatchedMediaFile
     */
    contentType?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedMediaFile
     */
    objectId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedMediaFile
     */
    fileName?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedMediaFile
     */
    fileSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedMediaFile
     */
    mimeType?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedMediaFile
     */
    fileData?: string;
}

/**
 * Check if a given object implements the PatchedMediaFile interface.
 */
export function instanceOfPatchedMediaFile(value: object): value is PatchedMediaFile {
    return true;
}

export function PatchedMediaFileFromJSON(json: any): PatchedMediaFile {
    return PatchedMediaFileFromJSONTyped(json, false);
}

export function PatchedMediaFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedMediaFile {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'objectId': json['object_id'] == null ? undefined : json['object_id'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'fileSize': json['file_size'] == null ? undefined : json['file_size'],
        'mimeType': json['mime_type'] == null ? undefined : json['mime_type'],
        'fileData': json['file_data'] == null ? undefined : json['file_data'],
    };
}

export function PatchedMediaFileToJSON(json: any): PatchedMediaFile {
    return PatchedMediaFileToJSONTyped(json, false);
}

export function PatchedMediaFileToJSONTyped(value?: PatchedMediaFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'object_id': value['objectId'],
        'file_name': value['fileName'],
        'file_size': value['fileSize'],
        'mime_type': value['mimeType'],
        'file_data': value['fileData'],
    };
}

