/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessRequestDurationPeriod } from './AccessRequestDurationPeriod';
import {
    AccessRequestDurationPeriodFromJSON,
    AccessRequestDurationPeriodFromJSONTyped,
    AccessRequestDurationPeriodToJSON,
    AccessRequestDurationPeriodToJSONTyped,
} from './AccessRequestDurationPeriod';
import type { DecisionEnum } from './DecisionEnum';
import {
    DecisionEnumFromJSON,
    DecisionEnumFromJSONTyped,
    DecisionEnumToJSON,
    DecisionEnumToJSONTyped,
} from './DecisionEnum';

/**
 * Access Request
 * @export
 * @interface PatchedAccessRequest
 */
export interface PatchedAccessRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    scopeType?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    scopeUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    role?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAccessRequest
     */
    endDate?: Date | null;
    /**
     * 
     * @type {AccessRequestDurationPeriod}
     * @memberof PatchedAccessRequest
     */
    durationPeriod?: AccessRequestDurationPeriod;
    /**
     * 
     * @type {number}
     * @memberof PatchedAccessRequest
     */
    durationValue?: number;
    /**
     * 
     * @type {DecisionEnum}
     * @memberof PatchedAccessRequest
     */
    decision?: DecisionEnum;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAccessRequest
     */
    readonly decisionDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAccessRequest
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessRequest
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAccessRequest
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedAccessRequest interface.
 */
export function instanceOfPatchedAccessRequest(value: object): value is PatchedAccessRequest {
    return true;
}

export function PatchedAccessRequestFromJSON(json: any): PatchedAccessRequest {
    return PatchedAccessRequestFromJSONTyped(json, false);
}

export function PatchedAccessRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAccessRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'scopeType': json['scope_type'] == null ? undefined : json['scope_type'],
        'scopeUuid': json['scope_uuid'] == null ? undefined : json['scope_uuid'],
        'user': json['user'] == null ? undefined : json['user'],
        'role': json['role'] == null ? undefined : json['role'],
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'durationPeriod': json['duration_period'] == null ? undefined : AccessRequestDurationPeriodFromJSON(json['duration_period']),
        'durationValue': json['duration_value'] == null ? undefined : json['duration_value'],
        'decision': json['decision'] == null ? undefined : DecisionEnumFromJSON(json['decision']),
        'decisionDate': json['decision_date'] == null ? undefined : (new Date(json['decision_date'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedAccessRequestToJSON(json: any): PatchedAccessRequest {
    return PatchedAccessRequestToJSONTyped(json, false);
}

export function PatchedAccessRequestToJSONTyped(value?: Omit<PatchedAccessRequest, 'id'|'decision_date'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'user': value['user'],
        'role': value['role'],
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'duration_period': AccessRequestDurationPeriodToJSON(value['durationPeriod']),
        'duration_value': value['durationValue'],
        'decision': DecisionEnumToJSON(value['decision']),
    };
}

