/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignmentMethodEnum } from './AssignmentMethodEnum';
import {
    AssignmentMethodEnumFromJSON,
    AssignmentMethodEnumFromJSONTyped,
    AssignmentMethodEnumToJSON,
    AssignmentMethodEnumToJSONTyped,
} from './AssignmentMethodEnum';

/**
 * Role Assignment
 * @export
 * @interface PatchedRoleAssignment
 */
export interface PatchedRoleAssignment {
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    scopeType?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    scopeUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    user?: string;
    /**
     * 
     * @type {AssignmentMethodEnum}
     * @memberof PatchedRoleAssignment
     */
    assignmentMethod?: AssignmentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    enrollmentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    accessRequest?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedRoleAssignment
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    readonly createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    readonly createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleAssignment
     */
    readonly modifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRoleAssignment
     */
    readonly modifiedAt?: Date | null;
}



/**
 * Check if a given object implements the PatchedRoleAssignment interface.
 */
export function instanceOfPatchedRoleAssignment(value: object): value is PatchedRoleAssignment {
    return true;
}

export function PatchedRoleAssignmentFromJSON(json: any): PatchedRoleAssignment {
    return PatchedRoleAssignmentFromJSONTyped(json, false);
}

export function PatchedRoleAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRoleAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'scopeType': json['scope_type'] == null ? undefined : json['scope_type'],
        'scopeUuid': json['scope_uuid'] == null ? undefined : json['scope_uuid'],
        'role': json['role'] == null ? undefined : json['role'],
        'user': json['user'] == null ? undefined : json['user'],
        'assignmentMethod': json['assignment_method'] == null ? undefined : AssignmentMethodEnumFromJSON(json['assignment_method']),
        'enrollmentMethod': json['enrollment_method'] == null ? undefined : json['enrollment_method'],
        'accessRequest': json['access_request'] == null ? undefined : json['access_request'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'modifiedBy': json['modified_by'] == null ? undefined : json['modified_by'],
        'modifiedAt': json['modified_at'] == null ? undefined : (new Date(json['modified_at'])),
    };
}

export function PatchedRoleAssignmentToJSON(json: any): PatchedRoleAssignment {
    return PatchedRoleAssignmentToJSONTyped(json, false);
}

export function PatchedRoleAssignmentToJSONTyped(value?: Omit<PatchedRoleAssignment, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'role': value['role'],
        'user': value['user'],
        'assignment_method': AssignmentMethodEnumToJSON(value['assignmentMethod']),
        'enrollment_method': value['enrollmentMethod'],
        'access_request': value['accessRequest'],
        'is_active': value['isActive'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

