/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Current User
 * @export
 * @interface PatchedCurrentUser
 */
export interface PatchedCurrentUser {
    /**
     * 
     * @type {number}
     * @memberof PatchedCurrentUser
     */
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    readonly fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    picture?: string | null;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof PatchedCurrentUser
     */
    isStaff?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCurrentUser
     */
    lastLogin?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCurrentUser
     */
    dateJoined?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedCurrentUser
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedCurrentUser
     */
    readonly isAuthenticated?: boolean;
}

/**
 * Check if a given object implements the PatchedCurrentUser interface.
 */
export function instanceOfPatchedCurrentUser(value: object): value is PatchedCurrentUser {
    return true;
}

export function PatchedCurrentUserFromJSON(json: any): PatchedCurrentUser {
    return PatchedCurrentUserFromJSONTyped(json, false);
}

export function PatchedCurrentUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCurrentUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'isStaff': json['is_staff'] == null ? undefined : json['is_staff'],
        'lastLogin': json['last_login'] == null ? undefined : (new Date(json['last_login'])),
        'dateJoined': json['date_joined'] == null ? undefined : (new Date(json['date_joined'])),
        'email': json['email'] == null ? undefined : json['email'],
        'isAuthenticated': json['is_authenticated'] == null ? undefined : json['is_authenticated'],
    };
}

export function PatchedCurrentUserToJSON(json: any): PatchedCurrentUser {
    return PatchedCurrentUserToJSONTyped(json, false);
}

export function PatchedCurrentUserToJSONTyped(value?: Omit<PatchedCurrentUser, 'id'|'full_name'|'is_authenticated'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'description': value['description'],
        'picture': value['picture'],
        'is_staff': value['isStaff'],
        'last_login': value['lastLogin'] == null ? undefined : ((value['lastLogin'] as any).toISOString()),
        'date_joined': value['dateJoined'] == null ? undefined : ((value['dateJoined']).toISOString()),
        'email': value['email'],
    };
}

