/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User
 * @export
 * @interface PatchedUser
 */
export interface PatchedUser {
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PatchedUser
     */
    readonly username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    readonly fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    picture?: string | null;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof PatchedUser
     */
    readonly isStaff?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    lastLogin?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedUser
     */
    dateJoined?: Date;
}

/**
 * Check if a given object implements the PatchedUser interface.
 */
export function instanceOfPatchedUser(value: object): value is PatchedUser {
    return true;
}

export function PatchedUserFromJSON(json: any): PatchedUser {
    return PatchedUserFromJSONTyped(json, false);
}

export function PatchedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'isStaff': json['is_staff'] == null ? undefined : json['is_staff'],
        'lastLogin': json['last_login'] == null ? undefined : (new Date(json['last_login'])),
        'dateJoined': json['date_joined'] == null ? undefined : (new Date(json['date_joined'])),
    };
}

export function PatchedUserToJSON(json: any): PatchedUser {
    return PatchedUserToJSONTyped(json, false);
}

export function PatchedUserToJSONTyped(value?: Omit<PatchedUser, 'id'|'username'|'full_name'|'is_staff'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'description': value['description'],
        'picture': value['picture'],
        'last_login': value['lastLogin'] == null ? undefined : ((value['lastLogin'] as any).toISOString()),
        'date_joined': value['dateJoined'] == null ? undefined : ((value['dateJoined']).toISOString()),
    };
}

