/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Permission
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {number}
     * @memberof Permission
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    codename: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    readonly permString: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    readonly permDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    readonly app: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    readonly appDisplayName: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    readonly model: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    readonly modelDisplayName: string;
}

/**
 * Check if a given object implements the Permission interface.
 */
export function instanceOfPermission(value: object): value is Permission {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('codename' in value) || value['codename'] === undefined) return false;
    if (!('permString' in value) || value['permString'] === undefined) return false;
    if (!('permDisplayName' in value) || value['permDisplayName'] === undefined) return false;
    if (!('app' in value) || value['app'] === undefined) return false;
    if (!('appDisplayName' in value) || value['appDisplayName'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('modelDisplayName' in value) || value['modelDisplayName'] === undefined) return false;
    return true;
}

export function PermissionFromJSON(json: any): Permission {
    return PermissionFromJSONTyped(json, false);
}

export function PermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Permission {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'codename': json['codename'],
        'permString': json['perm_string'],
        'permDisplayName': json['perm_display_name'],
        'app': json['app'],
        'appDisplayName': json['app_display_name'],
        'model': json['model'],
        'modelDisplayName': json['model_display_name'],
    };
}

export function PermissionToJSON(json: any): Permission {
    return PermissionToJSONTyped(json, false);
}

export function PermissionToJSONTyped(value?: Omit<Permission, 'id'|'perm_string'|'perm_display_name'|'app'|'app_display_name'|'model'|'model_display_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'codename': value['codename'],
    };
}

