/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reward Event
 * @export
 * @interface RewardEvent
 */
export interface RewardEvent {
    /**
     * 
     * @type {string}
     * @memberof RewardEvent
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof RewardEvent
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof RewardEvent
     */
    reward: string;
    /**
     * 
     * @type {string}
     * @memberof RewardEvent
     */
    eventType: string;
    /**
     * 
     * @type {number}
     * @memberof RewardEvent
     */
    pointsDelta: number;
    /**
     * 
     * @type {Date}
     * @memberof RewardEvent
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {any}
     * @memberof RewardEvent
     */
    context?: any | null;
}

/**
 * Check if a given object implements the RewardEvent interface.
 */
export function instanceOfRewardEvent(value: object): value is RewardEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('reward' in value) || value['reward'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('pointsDelta' in value) || value['pointsDelta'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RewardEventFromJSON(json: any): RewardEvent {
    return RewardEventFromJSONTyped(json, false);
}

export function RewardEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): RewardEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'account': json['account'],
        'reward': json['reward'],
        'eventType': json['event_type'],
        'pointsDelta': json['points_delta'],
        'createdAt': (new Date(json['created_at'])),
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function RewardEventToJSON(json: any): RewardEvent {
    return RewardEventToJSONTyped(json, false);
}

export function RewardEventToJSONTyped(value?: Omit<RewardEvent, 'id'|'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'reward': value['reward'],
        'event_type': value['eventType'],
        'points_delta': value['pointsDelta'],
        'context': value['context'],
    };
}

