/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignmentMethodEnum } from './AssignmentMethodEnum';
import {
    AssignmentMethodEnumFromJSON,
    AssignmentMethodEnumFromJSONTyped,
    AssignmentMethodEnumToJSON,
    AssignmentMethodEnumToJSONTyped,
} from './AssignmentMethodEnum';

/**
 * Role Assignment
 * @export
 * @interface RoleAssignment
 */
export interface RoleAssignment {
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    scopeType: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    scopeUuid: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    user: string;
    /**
     * 
     * @type {AssignmentMethodEnum}
     * @memberof RoleAssignment
     */
    assignmentMethod?: AssignmentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    enrollmentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    accessRequest?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RoleAssignment
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignment
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignment
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignment
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RoleAssignment
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof RoleAssignment
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the RoleAssignment interface.
 */
export function instanceOfRoleAssignment(value: object): value is RoleAssignment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function RoleAssignmentFromJSON(json: any): RoleAssignment {
    return RoleAssignmentFromJSONTyped(json, false);
}

export function RoleAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'role': json['role'],
        'user': json['user'],
        'assignmentMethod': json['assignment_method'] == null ? undefined : AssignmentMethodEnumFromJSON(json['assignment_method']),
        'enrollmentMethod': json['enrollment_method'] == null ? undefined : json['enrollment_method'],
        'accessRequest': json['access_request'] == null ? undefined : json['access_request'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function RoleAssignmentToJSON(json: any): RoleAssignment {
    return RoleAssignmentToJSONTyped(json, false);
}

export function RoleAssignmentToJSONTyped(value?: Omit<RoleAssignment, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'role': value['role'],
        'user': value['user'],
        'assignment_method': AssignmentMethodEnumToJSON(value['assignmentMethod']),
        'enrollment_method': value['enrollmentMethod'],
        'access_request': value['accessRequest'],
        'is_active': value['isActive'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
    };
}

