/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextFormatEnum } from './TextFormatEnum';
import {
    TextFormatEnumFromJSON,
    TextFormatEnumFromJSONTyped,
    TextFormatEnumToJSON,
    TextFormatEnumToJSONTyped,
} from './TextFormatEnum';

/**
 * Role
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    scopeType: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    scopeUuid: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    description?: string;
    /**
     * 
     * @type {TextFormatEnum}
     * @memberof Role
     */
    textFormat?: TextFormatEnum;
    /**
     * Low values mean less privileges. Make sure to correctly prioritize the rolls to avoid privilege escalation.
     * @type {number}
     * @memberof Role
     */
    priority: number;
    /**
     * 
     * @type {boolean}
     * @memberof Role
     */
    isActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Role
     */
    permissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Role
     */
    roleAssignments: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Role
     */
    enrollmentMethods: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Role
     */
    accessRequests: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    readonly createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Role
     */
    readonly createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Role
     */
    readonly modifiedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Role
     */
    readonly modifiedAt: Date | null;
}



/**
 * Check if a given object implements the Role interface.
 */
export function instanceOfRole(value: object): value is Role {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scopeType' in value) || value['scopeType'] === undefined) return false;
    if (!('scopeUuid' in value) || value['scopeUuid'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('roleAssignments' in value) || value['roleAssignments'] === undefined) return false;
    if (!('enrollmentMethods' in value) || value['enrollmentMethods'] === undefined) return false;
    if (!('accessRequests' in value) || value['accessRequests'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('modifiedBy' in value) || value['modifiedBy'] === undefined) return false;
    if (!('modifiedAt' in value) || value['modifiedAt'] === undefined) return false;
    return true;
}

export function RoleFromJSON(json: any): Role {
    return RoleFromJSONTyped(json, false);
}

export function RoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scopeType': json['scope_type'],
        'scopeUuid': json['scope_uuid'],
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'textFormat': json['text_format'] == null ? undefined : TextFormatEnumFromJSON(json['text_format']),
        'priority': json['priority'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'permissions': json['permissions'],
        'roleAssignments': json['role_assignments'],
        'enrollmentMethods': json['enrollment_methods'],
        'accessRequests': json['access_requests'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'modifiedBy': json['modified_by'],
        'modifiedAt': (json['modified_at'] == null ? null : new Date(json['modified_at'])),
    };
}

export function RoleToJSON(json: any): Role {
    return RoleToJSONTyped(json, false);
}

export function RoleToJSONTyped(value?: Omit<Role, 'id'|'created_by'|'created_at'|'modified_by'|'modified_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope_type': value['scopeType'],
        'scope_uuid': value['scopeUuid'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'text_format': TextFormatEnumToJSON(value['textFormat']),
        'priority': value['priority'],
        'is_active': value['isActive'],
        'permissions': value['permissions'],
        'role_assignments': value['roleAssignments'],
        'enrollment_methods': value['enrollmentMethods'],
        'access_requests': value['accessRequests'],
    };
}

