/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `TEXT` - Plain Text
 * * `HTML` - HTML
 * * `MD` - Markdown
 * @export
 */
export const TextFormatEnum = {
    Text: 'TEXT',
    Html: 'HTML',
    Md: 'MD'
} as const;
export type TextFormatEnum = typeof TextFormatEnum[keyof typeof TextFormatEnum];


export function instanceOfTextFormatEnum(value: any): boolean {
    for (const key in TextFormatEnum) {
        if (Object.prototype.hasOwnProperty.call(TextFormatEnum, key)) {
            if (TextFormatEnum[key as keyof typeof TextFormatEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TextFormatEnumFromJSON(json: any): TextFormatEnum {
    return TextFormatEnumFromJSONTyped(json, false);
}

export function TextFormatEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextFormatEnum {
    return json as TextFormatEnum;
}

export function TextFormatEnumToJSON(value?: TextFormatEnum | null): any {
    return value as any;
}

export function TextFormatEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): TextFormatEnum {
    return value as TextFormatEnum;
}

