/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerRewardEventLogRequest
 */
export interface TriggerRewardEventLogRequest {
    /**
     * 
     * @type {string}
     * @memberof TriggerRewardEventLogRequest
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof TriggerRewardEventLogRequest
     */
    reward: string;
    /**
     * 
     * @type {string}
     * @memberof TriggerRewardEventLogRequest
     */
    eventType?: string;
    /**
     * 
     * @type {any}
     * @memberof TriggerRewardEventLogRequest
     */
    context?: any | null;
}

/**
 * Check if a given object implements the TriggerRewardEventLogRequest interface.
 */
export function instanceOfTriggerRewardEventLogRequest(value: object): value is TriggerRewardEventLogRequest {
    if (!('reward' in value) || value['reward'] === undefined) return false;
    return true;
}

export function TriggerRewardEventLogRequestFromJSON(json: any): TriggerRewardEventLogRequest {
    return TriggerRewardEventLogRequestFromJSONTyped(json, false);
}

export function TriggerRewardEventLogRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerRewardEventLogRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : json['account'],
        'reward': json['reward'],
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function TriggerRewardEventLogRequestToJSON(json: any): TriggerRewardEventLogRequest {
    return TriggerRewardEventLogRequestToJSONTyped(json, false);
}

export function TriggerRewardEventLogRequestToJSONTyped(value?: TriggerRewardEventLogRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'reward': value['reward'],
        'event_type': value['eventType'],
        'context': value['context'],
    };
}

