/* tslint:disable */
/* eslint-disable */
/**
 * OpenBook API
 * Beautiful and Engaging Learning Materials
 *
 * The version of the OpenAPI document: 0.0.1-pre1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RewardEvent } from './RewardEvent';
import {
    RewardEventFromJSON,
    RewardEventFromJSONTyped,
    RewardEventToJSON,
    RewardEventToJSONTyped,
} from './RewardEvent';

/**
 * 
 * @export
 * @interface TriggerRewardEventResponse
 */
export interface TriggerRewardEventResponse {
    /**
     * 
     * @type {RewardEvent}
     * @memberof TriggerRewardEventResponse
     */
    rewardEvent: RewardEvent;
    /**
     * 
     * @type {number}
     * @memberof TriggerRewardEventResponse
     */
    pointTotal: number;
}

/**
 * Check if a given object implements the TriggerRewardEventResponse interface.
 */
export function instanceOfTriggerRewardEventResponse(value: object): value is TriggerRewardEventResponse {
    if (!('rewardEvent' in value) || value['rewardEvent'] === undefined) return false;
    if (!('pointTotal' in value) || value['pointTotal'] === undefined) return false;
    return true;
}

export function TriggerRewardEventResponseFromJSON(json: any): TriggerRewardEventResponse {
    return TriggerRewardEventResponseFromJSONTyped(json, false);
}

export function TriggerRewardEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerRewardEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'rewardEvent': RewardEventFromJSON(json['reward_event']),
        'pointTotal': json['point_total'],
    };
}

export function TriggerRewardEventResponseToJSON(json: any): TriggerRewardEventResponse {
    return TriggerRewardEventResponseToJSONTyped(json, false);
}

export function TriggerRewardEventResponseToJSONTyped(value?: TriggerRewardEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reward_event': RewardEventToJSON(value['rewardEvent']),
        'point_total': value['pointTotal'],
    };
}

