# Generated by Django 6.0.5 on 2026-06-09 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openbook_content', '0006_alter_textbookpage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningState',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Last Accessed')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_states', to='openbook_content.course', verbose_name='Course')),
                ('last_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_states', to='openbook_content.textbookpage', verbose_name='Last Page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_states', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Learning State',
                'verbose_name_plural': 'Learning States',
                'ordering': ['-last_accessed'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='openbook_learning_unique_user_course_state')],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('score', models.FloatField(help_text='Normalized score between 0.0 and 1.0.', verbose_name='Score')),
                ('attempts', models.PositiveIntegerField(default=1, verbose_name='Attempts')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Answered At')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='openbook_content.textbookpage', verbose_name='Page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz Result',
                'verbose_name_plural': 'Quiz Results',
                'ordering': ['-answered_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'page'), name='openbook_learning_unique_user_page_quiz')],
            },
        ),
    ]
