# Generated by Django 6.0.5 on 2026-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_content', '0006_alter_textbookpage_options'),
        ('openbook_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='completed_pages',
            field=models.ManyToManyField(blank=True, related_name='completed_in_states', to='openbook_content.textbookpage', verbose_name='Completed Pages'),
        ),
    ]
