# Generated by Django 6.0.5 on 2026-06-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_learning', '0002_learningstate_completed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
    ]
